import type { RegentRpcMethod } from "../../internal-types/index.js";

export const REGENT_RPC_METHODS = {
  runtimePing: "runtime.ping",
  runtimeStatus: "runtime.status",
  runtimeShutdown: "runtime.shutdown",
  agentInit: "agent.init",
  agentStatus: "agent.status",
  agentProfileList: "agent.profile.list",
  agentProfileShow: "agent.profile.show",
  agentHarnessList: "agent.harness.list",
  doctorRun: "doctor.run",
  doctorRunScoped: "doctor.runScoped",
  doctorRunFull: "doctor.runFull",
  authSiwaLogin: "auth.siwa.login",
  authSiwaLogout: "auth.siwa.logout",
  authSiwaStatus: "auth.siwa.status",
  techtreeStatus: "techtree.status",
  techtreeNodesList: "techtree.nodes.list",
  techtreeNodesGet: "techtree.nodes.get",
  techtreeNodesChildren: "techtree.nodes.children",
  techtreeNodesComments: "techtree.nodes.comments",
  techtreeActivityList: "techtree.activity.list",
  techtreeSearchQuery: "techtree.search.query",
  techtreeNodesWorkPacket: "techtree.nodes.workPacket",
  techtreeNodesCreate: "techtree.nodes.create",
  techtreeCommentsCreate: "techtree.comments.create",
  techtreeWatchCreate: "techtree.watch.create",
  techtreeWatchDelete: "techtree.watch.delete",
  techtreeWatchList: "techtree.watch.list",
  techtreeStarsCreate: "techtree.stars.create",
  techtreeStarsDelete: "techtree.stars.delete",
  techtreeInboxGet: "techtree.inbox.get",
  techtreeOpportunitiesList: "techtree.opportunities.list",
  techtreeTrollboxHistory: "techtree.trollbox.history",
  techtreeTrollboxPost: "techtree.trollbox.post",
  techtreeV1ArtifactInit: "techtree.v1.artifact.init",
  techtreeV1ArtifactCompile: "techtree.v1.artifact.compile",
  techtreeV1ArtifactPin: "techtree.v1.artifact.pin",
  techtreeV1ArtifactPublish: "techtree.v1.artifact.publish",
  techtreeV1RunInit: "techtree.v1.run.init",
  techtreeV1RunExec: "techtree.v1.run.exec",
  techtreeV1RunCompile: "techtree.v1.run.compile",
  techtreeV1RunPin: "techtree.v1.run.pin",
  techtreeV1RunPublish: "techtree.v1.run.publish",
  techtreeV1ReviewInit: "techtree.v1.review.init",
  techtreeV1ReviewExec: "techtree.v1.review.exec",
  techtreeV1ReviewCompile: "techtree.v1.review.compile",
  techtreeV1ReviewPin: "techtree.v1.review.pin",
  techtreeV1ReviewPublish: "techtree.v1.review.publish",
  techtreeV1Fetch: "techtree.v1.fetch",
  techtreeV1Verify: "techtree.v1.verify",
  techtreeV1BbhRunExec: "techtree.v1.bbh.run.exec",
  techtreeV1BbhAssignmentNext: "techtree.v1.bbh.assignment.next",
  techtreeV1BbhSubmit: "techtree.v1.bbh.submit",
  techtreeV1BbhValidate: "techtree.v1.bbh.validate",
  techtreeV1BbhLeaderboard: "techtree.v1.bbh.leaderboard",
  techtreeV1BbhSync: "techtree.v1.bbh.sync",
  xmtpStatus: "xmtp.status",
  gossipsubStatus: "gossipsub.status",
} as const satisfies Record<string, RegentRpcMethod>;

export const REGENT_RPC_METHOD_SET = new Set<RegentRpcMethod>(
  Object.values(REGENT_RPC_METHODS),
);
