"""Wallet sign-in (SIWA) and signed requests, the way the SIWA server checks them.

The agent key and each site's receipt live where the SIWA agent client keeps them:
`$SIWA_AGENT_HOME` (default `~/.siwa-agent`) holds `key.json` and `receipts/<site>.json`, so
the client and `regents` share one identity. The key holds a private key, the same key locked
with a passkey on a Mac (see `passkey`), or names a shell command that signs on Base or
Ethereum. `regents auth login --site <name>` signs in to that site's
audience and keeps the receipt; every wallet-proof request is then signed with the key.
Someone who keeps their own key instead signs the exact messages printed here.
"""

from __future__ import annotations

import base64
import hashlib
import json
import os
import re
import secrets
import subprocess
import sys
import time
from dataclasses import asdict, dataclass
from datetime import datetime
from functools import cache
from pathlib import Path
from typing import Any

import httpx
from eth_account import Account

from regents_cli import passkey
from regents_cli.errors import EXIT_AUTH, EXIT_UNREACHABLE, CommandError, UsageError
from regents_cli.http import Request, answer, origin

BASE = 8453
CHAINS = (BASE, 1)
BROKER = "https://siwa.regents.sh"
#: The signing contract, generated by the elixir-utils `siwa` library and pinned in
#: platforms.lock.json: the headers, covered components, signature parameters and lifetime every
#: SIWA signer and verifier follows. Its sha-256 is the contract id.
CONTRACT = Path(__file__).parent / "platforms" / "siwa" / "contract.json"
RENEW_MARGIN_SECONDS = 60
SIGNER_TIMEOUT_SECONDS = 300
ADDRESS = re.compile(r"0x[0-9a-fA-F]{40}")
SIGNATURE = re.compile(r"0x(?:[0-9a-fA-F]{2}){65,}")
SIGNER_OUTPUT = re.compile(r"0x[0-9a-fA-F]{130,}")
SIGNATURE_PARAM = re.compile(r';(?P<name>[a-z]+)=(?:(?P<integer>[1-9][0-9]*)|"(?P<text>[^";]+)")')


@cache
def contract() -> dict[str, Any]:
    contract: dict[str, Any] = json.loads(CONTRACT.read_text("utf-8"))
    return contract


def contract_id() -> str:
    """The id of the signing contract this regents signs with."""
    return hashlib.sha256(CONTRACT.read_bytes()).hexdigest()


def home() -> Path:
    return Path(os.environ.get("SIWA_AGENT_HOME", "~/.siwa-agent")).expanduser()


def broker() -> str:
    return origin(os.environ.get("SIWA_BROKER", BROKER).strip().rstrip("/"), "SIWA_BROKER")


def key_file() -> Path:
    return home() / "key.json"


def receipts_dir() -> Path:
    return home() / "receipts"


def receipt_file(site: str) -> Path:
    return receipts_dir() / f"{site}.json"


@dataclass(frozen=True, slots=True)
class Key:
    """The agent key: a private key, that key locked with a passkey, or the shell command that
    signs for `address` on `chain_id`."""

    address: str
    private_key: str | None = None
    locked: dict[str, str] | None = None
    signer: str | None = None
    chain_id: int = BASE


@dataclass(frozen=True, slots=True)
class Receipt:
    """A site's sign-in, as `receipts/<site>.json` holds it."""

    address: str
    audience: str
    receipt: str
    receipt_expires_at: str
    key_id: str

    def fresh(self, margin: int = 0) -> bool:
        expires = datetime.fromisoformat(self.receipt_expires_at.replace("Z", "+00:00"))
        return expires.timestamp() - time.time() > margin

    def signed_by(self, key: Key) -> bool:
        """Whether `key` is the one this receipt was issued to."""
        return key.address == self.address


def _write_private(path: Path, value: Any) -> None:
    path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    path.parent.chmod(0o700)
    temporary = path.with_suffix(".tmp")
    fd = os.open(temporary, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w", encoding="utf-8") as file:
        json.dump(value, file, indent=2)
    os.replace(temporary, path)


def _read_private(path: Path) -> Any:
    if not path.is_file():
        return None
    if path.stat().st_mode & 0o077:
        raise CommandError(
            "unsafe_file",
            f"{path} can be read by other users. Run chmod 600 {path}.",
            exit_code=EXIT_AUTH,
        )
    return json.loads(path.read_text("utf-8"))


def load_key() -> Key | None:
    stored = _read_private(key_file())
    if stored is None:
        return None
    if not (
        isinstance(stored, dict)
        and (
            set(stored) == {"address", "private_key"}
            or (
                set(stored) == {"address", "locked"}
                and isinstance(stored["locked"], dict)
                and set(stored["locked"]) == {"credential_id", "iv", "box"}
            )
            or (set(stored) == {"address", "signer", "chain_id"} and stored["chain_id"] in CHAINS)
        )
    ):
        raise CommandError(
            "bad_key_file",
            f"{key_file()} must hold an address and either a private_key, a locked key, or a "
            "signer with its chain_id (8453 for Base, 1 for Ethereum). Set it up again with "
            "the SIWA agent client's keygen or use-wallet.",
            exit_code=EXIT_AUTH,
        )
    return Key(**stored)


def create_key() -> Key:
    """Make the agent key. On a Mac it is locked with a passkey and kept unlocked by the helper
    until the Mac restarts; elsewhere the file holds the plain key."""
    account = Account.create()
    address, private_key = account.address.lower(), "0x" + bytes(account.key).hex()
    if sys.platform != "darwin":
        _write_private(key_file(), {"address": address, "private_key": private_key})
        return Key(address=address, private_key=private_key)
    key = Key(address=address, locked=passkey.lock(address, private_key))
    _write_private(key_file(), {"address": address, "locked": key.locked})
    passkey.start_helper(address, private_key)
    return key


def chain_for(address: str) -> int:
    """The chain a sign-in for `address` is on: the agent key's own when it is this machine's
    key, else Base, where an outside wallet signs in with --phase prepare."""
    key = load_key()
    return key.chain_id if key is not None and key.address == address.lower() else BASE


def load_receipt(site: str) -> Receipt | None:
    stored = _read_private(receipt_file(site))
    return Receipt(**stored) if stored is not None else None


def receipts() -> dict[str, Receipt]:
    """Every site's receipt, by site."""
    if not receipts_dir().is_dir():
        return {}
    found = (load_receipt(path.stem) for path in sorted(receipts_dir().glob("*.json")))
    return {receipt.audience: receipt for receipt in found if receipt is not None}


def remove_receipt(site: str) -> bool:
    path = receipt_file(site)
    if not path.is_file():
        return False
    path.unlink()
    return True


def personal_sign(key: Key, message: str) -> str:
    if key.signer is not None:
        return _run_signer(key.signer, message)
    if key.locked is not None:
        signature: str = passkey.unlocked(
            key.address, key.locked, {"op": "sign_message", "text": message}
        )["signature"]
        return signature
    assert key.private_key is not None
    return passkey.sign_message_with(key.private_key, message)


def sign_transaction(key: Key, transaction: dict[str, str]) -> str:
    """The raw signed transaction, given as the 0x fields `passkey.sign_transaction_with` takes."""
    if key.locked is not None:
        raw: str = passkey.unlocked(
            key.address, key.locked, {"op": "sign_transaction", "transaction": transaction}
        )["raw"]
        return raw
    assert key.private_key is not None
    return passkey.sign_transaction_with(key.private_key, transaction)


def _run_signer(command: str, message: str) -> str:
    """Hand the exact message to the key's signing command and read back its signature."""
    try:
        result = subprocess.run(
            command,
            shell=True,
            input=message,
            env={**os.environ, "SIWA_MESSAGE": message},
            capture_output=True,
            text=True,
            timeout=SIGNER_TIMEOUT_SECONDS,
        )
    except subprocess.TimeoutExpired:
        raise CommandError(
            "signer_failed",
            f"The signing command did not answer within {SIGNER_TIMEOUT_SECONDS} seconds.",
            exit_code=EXIT_AUTH,
        ) from None
    if result.returncode != 0:
        said = result.stderr.strip() or result.stdout.strip()
        raise CommandError(
            "signer_failed",
            f"The signing command exited {result.returncode}" + (f": {said}" if said else "."),
            exit_code=EXIT_AUTH,
        )
    found: set[str] = set(SIGNER_OUTPUT.findall(result.stdout))
    if len(found) != 1:
        raise CommandError(
            "signer_failed",
            "The signing command must print exactly one 0x signature; it printed: "
            f"{result.stdout.strip()}",
            exit_code=EXIT_AUTH,
        )
    return found.pop()


def _post(
    path: str,
    body: dict[str, Any],
    timeout_ms: int,
    headers: dict[str, str] | None = None,
) -> Any:
    address = broker()
    try:
        response = httpx.post(
            address + path,
            json=body,
            headers=headers,
            timeout=timeout_ms / 1000,
            follow_redirects=False,
        )
    except httpx.HTTPError:
        raise CommandError(
            "unreachable",
            f"The sign-in server {address} could not be reached, or did not answer in time.",
            exit_code=EXIT_UNREACHABLE,
            hint="Check that it is up and the address is right: SIWA_BROKER names another.",
        ) from None
    return answer(response)


def challenge(site: str, wallet_address: str, timeout_ms: int) -> dict[str, str]:
    """Ask the sign-in server for the message this wallet signs to sign in to `site`."""
    if not ADDRESS.fullmatch(wallet_address):
        raise UsageError(f"{wallet_address!r} is not an address.")
    issued = _post(
        "/api/shared/siwa/wallet/nonce",
        {"wallet_address": wallet_address, "chain_id": chain_for(wallet_address), "audience": site},
        timeout_ms,
    )
    data = issued["data"]
    return {
        "wallet_address": wallet_address.lower(),
        "nonce": data["nonce"],
        "message": data["message"],
    }


def verify(site: str, signed: dict[str, str], timeout_ms: int) -> Receipt:
    """Hand the signed challenge back and keep the receipt for `site`."""
    verified = _post(
        "/api/shared/siwa/wallet/verify",
        {"chain_id": chain_for(signed["wallet_address"]), "audience": site, **signed},
        timeout_ms,
    )
    data = verified["data"]
    receipt = Receipt(
        address=data["walletAddress"],
        audience=site,
        receipt=data["receipt"],
        receipt_expires_at=data["receiptExpiresAt"],
        key_id=data["keyId"],
    )
    _write_private(receipt_file(site), asdict(receipt))
    return receipt


def sign_in_with_key(site: str, key: Key, timeout_ms: int) -> Receipt:
    issued = challenge(site, key.address, timeout_ms)
    signed = {**issued, "signature": personal_sign(key, issued["message"])}
    return verify(site, signed, timeout_ms)


def current(site: str, timeout_ms: int) -> Receipt:
    """This site's receipt, renewed first when the key on this machine signed in."""
    receipt = load_receipt(site)
    if receipt is None:
        raise CommandError(
            "not_signed_in",
            f"Sign in first: regents auth login --site {site}.",
            exit_code=EXIT_AUTH,
        )
    if receipt.fresh(RENEW_MARGIN_SECONDS):
        return receipt
    key = load_key()
    if key is not None and receipt.signed_by(key):
        return sign_in_with_key(site, key, timeout_ms)
    raise CommandError(
        "sign_in_expired",
        f"The sign-in to {site} has expired. Sign in again with regents auth login --site {site}.",
        exit_code=EXIT_AUTH,
    )


def unsigned(
    request: Request,
    *,
    receipt: str,
    wallet_address: str,
    chain_id: int,
    key_id: str,
    created: int,
    expires: int,
    nonce: str,
) -> tuple[dict[str, str], str]:
    """The request's signed headers, less the signature, and the message to personal_sign.

    The contract names each covered component and signature parameter and the value it comes
    `from`; a body adds its digest last. Integer parameters are bare and text ones quoted.
    """
    rules = contract()
    values: dict[str, str | int] = {
        "method": request.method.lower(),
        "path": request.target,
        "receipt": receipt,
        "key_id": key_id,
        "created": created,
        "expires": expires,
        "nonce": nonce,
        "wallet_address": wallet_address,
        "chain_id": chain_id,
    }
    covered = {c["name"]: str(values[c["from"]]) for c in rules["components"]}
    if (content := request.content) is not None:
        body = rules["body"]
        digest = hashlib.new(body["algorithm"].replace("-", ""), content).digest()
        covered[body["component"]] = f"{body['algorithm']}=:{base64.b64encode(digest).decode()}:"
    params = (
        "("
        + " ".join(f'"{name}"' for name in covered)
        + ")"
        + "".join(f";{p['name']}={_param_value(values[p['from']])}" for p in rules["params"])
    )
    headers = {name: value for name, value in covered.items() if not name.startswith("@")}
    headers[rules["signature_input_header"]] = f"{rules['label']}={params}"
    lines = [f'"{name}": {value}' for name, value in covered.items()]
    return headers, "\n".join([*lines, f'"@signature-params": {params}'])


def _param_value(value: str | int) -> str:
    return str(value) if isinstance(value, int) else f'"{value}"'


def header_for(source: str) -> str:
    """The header that carries the value `from` `source`."""
    [header] = [c["name"] for c in contract()["components"] if c["from"] == source]
    return str(header)


def prepare(request: Request, receipt: Receipt) -> tuple[dict[str, str], str]:
    created = int(time.time())
    return unsigned(
        request,
        receipt=receipt.receipt,
        wallet_address=receipt.address,
        chain_id=chain_for(receipt.address),
        key_id=receipt.key_id,
        created=created,
        expires=created + contract()["lifetime_seconds"],
        nonce="sig-nonce-" + secrets.token_hex(16),
    )


def rebuild(request: Request, headers: dict[str, str]) -> tuple[dict[str, str], str]:
    """The headers and message `prepare` gave for `request`, read back from its headers.

    Anything other than exactly what `prepare` printed for this request is refused.
    """
    rules = contract()
    signature_input = headers.get(rules["signature_input_header"], "")
    found = {
        m["name"]: int(m["integer"]) if m["integer"] else m["text"]
        for m in SIGNATURE_PARAM.finditer(signature_input)
    }
    given = {p["from"]: found.get(p["name"]) for p in rules["params"]}
    if not (
        isinstance(given["created"], int)
        and isinstance(given["expires"], int)
        and isinstance(given["nonce"], str)
        and isinstance(given["key_id"], str)
    ):
        raise UsageError("The request's signature input is not one regents prepared.")
    wallet_address = headers.get(header_for("wallet_address"), "")
    expected, message = unsigned(
        request,
        receipt=headers.get(header_for("receipt"), ""),
        wallet_address=wallet_address,
        chain_id=chain_for(wallet_address),
        key_id=given["key_id"],
        created=given["created"],
        expires=given["expires"],
        nonce=given["nonce"],
    )
    if expected != headers:
        raise UsageError("The request's headers are not the ones regents prepared for it.")
    return expected, message


def with_signature(headers: dict[str, str], signature: str) -> dict[str, str]:
    """The signed headers: `headers` plus the 0x `signature` of their message."""
    if not SIGNATURE.fullmatch(signature):
        raise UsageError("The signature must be 0x followed by 130 or more hex characters.")
    rules = contract()
    encoded = base64.b64encode(bytes.fromhex(signature[2:])).decode("ascii")
    return {**headers, rules["signature_header"]: f"{rules['label']}=:{encoded}:"}


def sign(request: Request, receipt: Receipt) -> dict[str, str]:
    """Signed headers for `request`, signed with the key on this machine."""
    key = load_key()
    if key is None or not receipt.signed_by(key):
        raise CommandError(
            "outside_key",
            "This site's sign-in belongs to a key that is not on this machine. "
            "Sign with it yourself: --phase prepare, then --phase send.",
            exit_code=EXIT_AUTH,
        )
    headers, message = prepare(request, receipt)
    return with_signature(headers, personal_sign(key, message))


def confirm(site: str, receipt: Receipt, timeout_ms: int) -> dict[str, Any]:
    """Have the sign-in server check a request signed with this sign-in, as the site does.

    Answers what the sign-in server tells the site about the wallet: its agent registry
    listing (`agentRegistration`) and the World ID person it accepted (`agentBook`), each
    None when it has none.
    """
    request = Request("GET", "/")
    checked = _post(
        "/api/shared/siwa/http-verify",
        {"method": request.method, "path": request.target, "headers": sign(request, receipt)},
        timeout_ms,
        headers={"x-siwa-audience": site},
    )
    if not isinstance(checked, dict) or checked.get("code") != "http_envelope_valid":
        raise CommandError(
            "sign_in_refused",
            f"The sign-in server did not accept a request signed for {site}.",
            exit_code=EXIT_AUTH,
        )
    told: dict[str, Any] = checked["data"]
    return told


def registration_step(profile: dict[str, str], timeout_ms: int) -> dict[str, Any]:
    """The one transaction that lists `profile` in the agent registry, for its wallet to send."""
    step: dict[str, Any] = _post("/api/shared/siwa/agent/register-step", profile, timeout_ms)[
        "data"
    ]
    return step


def registration_outcome(profile: dict[str, str], tx_hash: str, timeout_ms: int) -> dict[str, Any]:
    """What the sign-in server read of the registration sent as `tx_hash`, at the latest block:
    `registration_pending` until it lands, then `agent_registered` with the listing."""
    outcome: dict[str, Any] = _post(
        "/api/shared/siwa/agent/registered", {**profile, "tx_hash": tx_hash}, timeout_ms
    )
    return outcome


def signer_name(key: Key) -> str:
    """How this machine's key signs, so the sign-in server can word its advice on a refusal."""
    if key.signer is None:
        return "own-key"
    return Path((key.signer.split() or [""])[0]).name


def agent_book_challenge(wallet_address: str, timeout_ms: int) -> dict[str, Any]:
    """The person World's AgentBook names behind this wallet now, and the message the wallet
    signs to accept them."""
    if not ADDRESS.fullmatch(wallet_address):
        raise UsageError(f"{wallet_address!r} is not an address.")
    data = _post(
        "/api/shared/siwa/agent-book/challenge",
        {"wallet_address": wallet_address, "chain_id": chain_for(wallet_address)},
        timeout_ms,
    )["data"]
    return {
        "wallet_address": data["walletAddress"],
        "human_id": data["humanId"],
        "nonce": data["nonce"],
        "message": data["message"],
    }


def accept_agent_book(
    signed: dict[str, str], signer: str | None, timeout_ms: int
) -> dict[str, Any]:
    """Hand the signed challenge back; the sign-in server keeps the person for good."""
    data = _post(
        "/api/shared/siwa/agent-book/accept",
        {"chain_id": chain_for(signed["wallet_address"]), **signed},
        timeout_ms,
        headers={"x-agent-signer": signer} if signer is not None else None,
    )["data"]
    return {"wallet_address": data["walletAddress"], "human_id": data["humanId"]}
