import {
  runAutolaunchContractsAdminShow,
  runAutolaunchContractsJobShow,
  runAutolaunchContractsSubjectShow,
  runAutolaunchAgentsList,
  runAutolaunchAgentReadiness,
  runAutolaunchAgentShow,
  runAutolaunchAuctionsList,
  runAutolaunchAuctionReturnsList,
  runAutolaunchAuctionShow,
  runAutolaunchBidsClaim,
  runAutolaunchBidsExit,
  runAutolaunchBidsPlace,
  runAutolaunchBidsQuote,
  runAutolaunchEnsPlan,
  runAutolaunchEnsPrepareBidirectional,
  runAutolaunchEnsPrepareErc8004,
  runAutolaunchEnsPrepareEnsip25,
  runAutolaunchFeeRegistryGet,
  runAutolaunchFeeVaultGet,
  runAutolaunchFeeVaultWithdrawRegent,
  runAutolaunchIdentitiesList,
  runAutolaunchIdentitiesMint,
  runAutolaunchIngressCreate,
  runAutolaunchIngressRescue,
  runAutolaunchIngressSetDefault,
  runAutolaunchIngressSetLabel,
  runAutolaunchJobsWatch,
  runAutolaunchConnectStart,
  runAutolaunchAuctionState,
  runAutolaunchPair,
  runAutolaunchPaymentLinkCreate,
  runAutolaunchPaymentLinkSetCanonical,
  runAutolaunchPaymentLinkSetState,
  runAutolaunchLaunchFinalize,
  runAutolaunchLaunchMonitor,
  runAutolaunchLaunchPreview,
  runAutolaunchLaunchRun,
  runAutolaunchLaunchState,
  runAutolaunchSafeCreate,
  runAutolaunchSafeWizard,
  runAutolaunchPrelaunchPublish,
  runAutolaunchPrelaunchGet,
  runAutolaunchPrelaunchValidate,
  runAutolaunchPrelaunchWizard,
  runAutolaunchRegistryLinkIdentity,
  runAutolaunchRegistryRotateSafe,
  runAutolaunchRegistrySetSubjectManager,
  runAutolaunchRegistryGet,
  runAutolaunchRevenueIngressFactorySetAuthorizedCreator,
  runAutolaunchRevenueShareFactorySetAuthorizedCreator,
  runAutolaunchSplitterAcceptOwnership,
  runAutolaunchSplitterActivateEligibleRevenueShare,
  runAutolaunchSplitterCancelEligibleRevenueShare,
  runAutolaunchSplitterCancelTreasuryRecipientRotation,
  runAutolaunchSplitterExecuteTreasuryRecipientRotation,
  runAutolaunchSplitterProposeEligibleRevenueShare,
  runAutolaunchSplitterProposeTreasuryRecipientRotation,
  runAutolaunchSplitterReassignDust,
  runAutolaunchSplitterSetLabel,
  runAutolaunchSplitterSetPaused,
  runAutolaunchSplitterSweepTreasuryReserved,
  runAutolaunchSplitterSweepTreasuryResidual,
  runAutolaunchSplitterGet,
  runAutolaunchStrategyMigrate,
  runAutolaunchStrategySweepQuoteToken,
  runAutolaunchStrategySweepToken,
  runAutolaunchSubjectByToken,
  runAutolaunchSubjectClaimUsdc,
  runAutolaunchSubjectCreateDeferredAutolaunch,
  runAutolaunchSubjectCreateExistingToken,
  runAutolaunchSubjectBuybacks,
  runAutolaunchSubjectIngress,
  runAutolaunchSubjectGet,
  runAutolaunchSubjectPaymentLinks,
  runAutolaunchSubjectRegentEmissions,
  runAutolaunchSubjectSettleBuyback,
  runAutolaunchSubjectStake,
  runAutolaunchSubjectStaking,
  runAutolaunchSubjectSweepIngress,
  runAutolaunchSubjectUnstake,
  runAutolaunchVestingCancelBeneficiaryRotation,
  runAutolaunchVestingExecuteBeneficiaryRotation,
  runAutolaunchVestingProposeBeneficiaryRotation,
  runAutolaunchVestingRelease,
  runAutolaunchVestingStatus,
} from "../commands/autolaunch.js";
import { requireArg } from "../parse.js";
import type { CliHandlerRegistry } from "./shared.js";

export const autolaunchHandlers: CliHandlerRegistry = {
  "autolaunch agents list": { run: ({ parsedArgs, configPath }) => runAutolaunchAgentsList(parsedArgs, configPath) },
  // Placeholder-bearing commands extract their id from positionals by index.
  "autolaunch agent readiness <id>": {
    run: ({ positionals, configPath }) => runAutolaunchAgentReadiness(requireArg(positionals[3], "agent-id"), configPath),
  },
  "autolaunch agent <id>": {
    run: ({ positionals, configPath }) => runAutolaunchAgentShow(positionals[2] as string, configPath),
  },
  "autolaunch auctions list": { run: ({ parsedArgs, configPath }) => runAutolaunchAuctionsList(parsedArgs, configPath) },
  "autolaunch auction-returns list": { run: ({ parsedArgs, configPath }) => runAutolaunchAuctionReturnsList(parsedArgs, configPath) },
  "autolaunch auction <id>": {
    run: ({ positionals, configPath }) => runAutolaunchAuctionShow(positionals[2] as string, configPath),
  },
  "autolaunch auction state <id>": {
    run: ({ parsedArgs, positionals, configPath }) =>
      runAutolaunchAuctionState(requireArg(positionals[3], "auction-id"), parsedArgs, configPath),
  },
  "autolaunch bids quote": { run: ({ parsedArgs, configPath }) => runAutolaunchBidsQuote(parsedArgs, configPath) },
  "autolaunch bids place": { run: ({ parsedArgs, configPath }) => runAutolaunchBidsPlace(parsedArgs, configPath) },
  "autolaunch bids exit": { run: ({ parsedArgs, configPath }) => runAutolaunchBidsExit(parsedArgs, configPath) },
  "autolaunch bids claim": { run: ({ parsedArgs, configPath }) => runAutolaunchBidsClaim(parsedArgs, configPath) },
  "autolaunch ens plan": { run: ({ parsedArgs, configPath }) => runAutolaunchEnsPlan(parsedArgs, configPath) },
  "autolaunch ens prepare-ensip25": { run: ({ parsedArgs, configPath }) => runAutolaunchEnsPrepareEnsip25(parsedArgs, configPath) },
  "autolaunch ens prepare-erc8004": { run: ({ parsedArgs, configPath }) => runAutolaunchEnsPrepareErc8004(parsedArgs, configPath) },
  "autolaunch ens prepare-bidirectional": { run: ({ parsedArgs, configPath }) => runAutolaunchEnsPrepareBidirectional(parsedArgs, configPath) },
  "autolaunch identities list": { run: ({ parsedArgs }) => runAutolaunchIdentitiesList(parsedArgs) },
  "autolaunch identities mint": { run: ({ parsedArgs }) => runAutolaunchIdentitiesMint(parsedArgs) },
  "autolaunch pair": { run: ({ parsedArgs, configPath }) => runAutolaunchPair(parsedArgs, configPath) },
  "autolaunch connect start": { run: ({ parsedArgs, configPath }) => runAutolaunchConnectStart(parsedArgs, configPath) },
  "autolaunch prelaunch wizard": { run: ({ parsedArgs, configPath }) => runAutolaunchPrelaunchWizard(parsedArgs, configPath) },
  "autolaunch safe wizard": { run: ({ parsedArgs, configPath }) => runAutolaunchSafeWizard(parsedArgs, configPath) },
  "autolaunch safe create": { run: ({ parsedArgs, configPath }) => runAutolaunchSafeCreate(parsedArgs, configPath) },
  "autolaunch prelaunch get": { run: ({ parsedArgs, configPath }) => runAutolaunchPrelaunchGet(parsedArgs, configPath) },
  "autolaunch prelaunch validate": { run: ({ parsedArgs, configPath }) => runAutolaunchPrelaunchValidate(parsedArgs, configPath) },
  "autolaunch prelaunch publish": { run: ({ parsedArgs, configPath }) => runAutolaunchPrelaunchPublish(parsedArgs, configPath) },
  "autolaunch launch preview": { run: ({ parsedArgs, configPath }) => runAutolaunchLaunchPreview(parsedArgs, configPath) },
  "autolaunch launch run": { run: ({ parsedArgs, configPath }) => runAutolaunchLaunchRun(parsedArgs, configPath) },
  "autolaunch launch state": { run: ({ parsedArgs, configPath }) => runAutolaunchLaunchState(parsedArgs, configPath) },
  "autolaunch launch monitor": { run: ({ parsedArgs, configPath }) => runAutolaunchLaunchMonitor(parsedArgs, configPath), variadicTail: true },
  "autolaunch launch finalize": { run: ({ parsedArgs, configPath }) => runAutolaunchLaunchFinalize(parsedArgs, configPath) },
  "autolaunch jobs watch": { run: ({ parsedArgs, configPath }) => runAutolaunchJobsWatch(parsedArgs, configPath), variadicTail: true },
  // Subject commands match an extra `<subject-id>` value slot beyond the command name.
  "autolaunch subjects get": { run: ({ parsedArgs, configPath }) => runAutolaunchSubjectGet(parsedArgs, configPath), pattern: "autolaunch subjects get <subject-id>" },
  "autolaunch subjects create-existing-token": { run: ({ parsedArgs, configPath }) => runAutolaunchSubjectCreateExistingToken(parsedArgs, configPath) },
  "autolaunch subjects create-deferred-autolaunch": { run: ({ parsedArgs, configPath }) => runAutolaunchSubjectCreateDeferredAutolaunch(parsedArgs, configPath) },
  "autolaunch subjects by-token": { run: ({ parsedArgs, configPath }) => runAutolaunchSubjectByToken(parsedArgs, configPath) },
  "autolaunch subjects ingress": { run: ({ parsedArgs, configPath }) => runAutolaunchSubjectIngress(parsedArgs, configPath), pattern: "autolaunch subjects ingress <subject-id>" },
  "autolaunch subjects staking": { run: ({ parsedArgs, configPath }) => runAutolaunchSubjectStaking(parsedArgs, configPath), pattern: "autolaunch subjects staking <subject-id>" },
  "autolaunch subjects stake": { run: ({ parsedArgs, configPath }) => runAutolaunchSubjectStake(parsedArgs, configPath), pattern: "autolaunch subjects stake <subject-id>" },
  "autolaunch subjects unstake": { run: ({ parsedArgs, configPath }) => runAutolaunchSubjectUnstake(parsedArgs, configPath), pattern: "autolaunch subjects unstake <subject-id>" },
  "autolaunch subjects claim-usdc": { run: ({ parsedArgs, configPath }) => runAutolaunchSubjectClaimUsdc(parsedArgs, configPath), pattern: "autolaunch subjects claim-usdc <subject-id>" },
  "autolaunch subjects sweep-ingress": { run: ({ parsedArgs, configPath }) => runAutolaunchSubjectSweepIngress(parsedArgs, configPath), pattern: "autolaunch subjects sweep-ingress <subject-id>" },
  "autolaunch subjects buybacks": { run: ({ parsedArgs, configPath }) => runAutolaunchSubjectBuybacks(parsedArgs, configPath), pattern: "autolaunch subjects buybacks <subject-id>" },
  "autolaunch subjects settle-buyback": { run: ({ parsedArgs, configPath }) => runAutolaunchSubjectSettleBuyback(parsedArgs, configPath), pattern: "autolaunch subjects settle-buyback <subject-id>" },
  "autolaunch subjects payment-links": { run: ({ parsedArgs, configPath }) => runAutolaunchSubjectPaymentLinks(parsedArgs, configPath), pattern: "autolaunch subjects payment-links <subject-id>" },
  "autolaunch payment-links create": { run: ({ parsedArgs, configPath }) => runAutolaunchPaymentLinkCreate(parsedArgs, configPath) },
  "autolaunch payment-links set-canonical": { run: ({ parsedArgs, configPath }) => runAutolaunchPaymentLinkSetCanonical(parsedArgs, configPath) },
  "autolaunch payment-links set-state": { run: ({ parsedArgs, configPath }) => runAutolaunchPaymentLinkSetState(parsedArgs, configPath) },
  "autolaunch subjects regent-emissions": { run: ({ parsedArgs, configPath }) => runAutolaunchSubjectRegentEmissions(parsedArgs, configPath), pattern: "autolaunch subjects regent-emissions <subject-id>" },
  "autolaunch contracts admin": { run: ({ configPath }) => runAutolaunchContractsAdminShow(configPath) },
  "autolaunch contracts job": { run: ({ parsedArgs, configPath }) => runAutolaunchContractsJobShow(parsedArgs, configPath) },
  "autolaunch contracts subject": { run: ({ parsedArgs, configPath }) => runAutolaunchContractsSubjectShow(parsedArgs, configPath) },
  "autolaunch strategy migrate": { run: ({ parsedArgs, configPath }) => runAutolaunchStrategyMigrate(parsedArgs, configPath) },
  "autolaunch strategy sweep-token": { run: ({ parsedArgs, configPath }) => runAutolaunchStrategySweepToken(parsedArgs, configPath) },
  "autolaunch strategy sweep-quote-token": { run: ({ parsedArgs, configPath }) => runAutolaunchStrategySweepQuoteToken(parsedArgs, configPath) },
  "autolaunch vesting release": { run: ({ parsedArgs, configPath }) => runAutolaunchVestingRelease(parsedArgs, configPath) },
  "autolaunch vesting propose-beneficiary-rotation": { run: ({ parsedArgs, configPath }) => runAutolaunchVestingProposeBeneficiaryRotation(parsedArgs, configPath) },
  "autolaunch vesting cancel-beneficiary-rotation": { run: ({ parsedArgs, configPath }) => runAutolaunchVestingCancelBeneficiaryRotation(parsedArgs, configPath) },
  "autolaunch vesting execute-beneficiary-rotation": { run: ({ parsedArgs, configPath }) => runAutolaunchVestingExecuteBeneficiaryRotation(parsedArgs, configPath) },
  "autolaunch vesting status": { run: ({ parsedArgs, configPath }) => runAutolaunchVestingStatus(parsedArgs, configPath) },
  "autolaunch fee-registry get": { run: ({ parsedArgs, configPath }) => runAutolaunchFeeRegistryGet(parsedArgs, configPath) },
  "autolaunch fee-vault get": { run: ({ parsedArgs, configPath }) => runAutolaunchFeeVaultGet(parsedArgs, configPath) },
  "autolaunch fee-vault withdraw-regent": { run: ({ parsedArgs, configPath }) => runAutolaunchFeeVaultWithdrawRegent(parsedArgs, configPath) },
  "autolaunch splitter get": { run: ({ parsedArgs, configPath }) => runAutolaunchSplitterGet(parsedArgs, configPath) },
  "autolaunch splitter accept-ownership": { run: ({ parsedArgs, configPath }) => runAutolaunchSplitterAcceptOwnership(parsedArgs, configPath) },
  "autolaunch splitter set-paused": { run: ({ parsedArgs, configPath }) => runAutolaunchSplitterSetPaused(parsedArgs, configPath) },
  "autolaunch splitter set-label": { run: ({ parsedArgs, configPath }) => runAutolaunchSplitterSetLabel(parsedArgs, configPath) },
  "autolaunch splitter propose-eligible-revenue-share": { run: ({ parsedArgs, configPath }) => runAutolaunchSplitterProposeEligibleRevenueShare(parsedArgs, configPath) },
  "autolaunch splitter cancel-eligible-revenue-share": { run: ({ parsedArgs, configPath }) => runAutolaunchSplitterCancelEligibleRevenueShare(parsedArgs, configPath) },
  "autolaunch splitter activate-eligible-revenue-share": { run: ({ parsedArgs, configPath }) => runAutolaunchSplitterActivateEligibleRevenueShare(parsedArgs, configPath) },
  "autolaunch splitter propose-treasury-recipient-rotation": { run: ({ parsedArgs, configPath }) => runAutolaunchSplitterProposeTreasuryRecipientRotation(parsedArgs, configPath) },
  "autolaunch splitter cancel-treasury-recipient-rotation": { run: ({ parsedArgs, configPath }) => runAutolaunchSplitterCancelTreasuryRecipientRotation(parsedArgs, configPath) },
  "autolaunch splitter execute-treasury-recipient-rotation": { run: ({ parsedArgs, configPath }) => runAutolaunchSplitterExecuteTreasuryRecipientRotation(parsedArgs, configPath) },
  "autolaunch splitter sweep-treasury-residual": { run: ({ parsedArgs, configPath }) => runAutolaunchSplitterSweepTreasuryResidual(parsedArgs, configPath) },
  "autolaunch splitter sweep-treasury-reserved": { run: ({ parsedArgs, configPath }) => runAutolaunchSplitterSweepTreasuryReserved(parsedArgs, configPath) },
  "autolaunch splitter reassign-dust": { run: ({ parsedArgs, configPath }) => runAutolaunchSplitterReassignDust(parsedArgs, configPath) },
  "autolaunch ingress create": { run: ({ parsedArgs, configPath }) => runAutolaunchIngressCreate(parsedArgs, configPath) },
  "autolaunch ingress set-default": { run: ({ parsedArgs, configPath }) => runAutolaunchIngressSetDefault(parsedArgs, configPath) },
  "autolaunch ingress set-label": { run: ({ parsedArgs, configPath }) => runAutolaunchIngressSetLabel(parsedArgs, configPath) },
  "autolaunch ingress rescue": { run: ({ parsedArgs, configPath }) => runAutolaunchIngressRescue(parsedArgs, configPath) },
  "autolaunch registry get": { run: ({ parsedArgs, configPath }) => runAutolaunchRegistryGet(parsedArgs, configPath) },
  "autolaunch registry set-subject-manager": { run: ({ parsedArgs, configPath }) => runAutolaunchRegistrySetSubjectManager(parsedArgs, configPath) },
  "autolaunch registry link-identity": { run: ({ parsedArgs, configPath }) => runAutolaunchRegistryLinkIdentity(parsedArgs, configPath) },
  "autolaunch registry rotate-safe": { run: ({ parsedArgs, configPath }) => runAutolaunchRegistryRotateSafe(parsedArgs, configPath) },
  "autolaunch factory revenue-share set-authorized-creator": { run: ({ parsedArgs, configPath }) => runAutolaunchRevenueShareFactorySetAuthorizedCreator(parsedArgs, configPath) },
  "autolaunch factory revenue-ingress set-authorized-creator": { run: ({ parsedArgs, configPath }) => runAutolaunchRevenueIngressFactorySetAuthorizedCreator(parsedArgs, configPath) },
};
