import {
  runPlatformAuthLogin,
  runPlatformAuthLogout,
  runPlatformAuthStatus,
  runPlatformBillingAccount,
  runPlatformBillingSpendControlsSet,
  runPlatformBillingTopup,
  runPlatformBillingUsage,
  runPlatformRegentPause,
  runPlatformRegentResume,
  runPlatformRegentRuntime,
  runPlatformFormationDoctor,
  runPlatformFormationStatus,
  runPlatformProjection,
} from "../commands/platform.js";
import {
  runServiceCatalogCheck,
  runServiceInit,
  runServiceLogs,
  runServicePause,
  runServicePriceSet,
  runServicePublish,
  runServiceResume,
  runServiceRuns,
  runServiceTest,
} from "../commands/platform-services.js";
import type { CliHandlerRegistry } from "./shared.js";

export const platformHandlers: CliHandlerRegistry = {
  "platform auth login": { run: ({ parsedArgs }) => runPlatformAuthLogin(parsedArgs) },
  "platform auth status": { run: ({ parsedArgs }) => runPlatformAuthStatus(parsedArgs) },
  "platform auth logout": { run: ({ parsedArgs }) => runPlatformAuthLogout(parsedArgs) },
  "platform formation status": { run: ({ parsedArgs }) => runPlatformFormationStatus(parsedArgs) },
  "platform formation doctor": { run: ({ parsedArgs }) => runPlatformFormationDoctor(parsedArgs) },
  "platform projection": { run: ({ parsedArgs }) => runPlatformProjection(parsedArgs) },
  "platform billing account": { run: ({ parsedArgs }) => runPlatformBillingAccount(parsedArgs) },
  "platform billing usage": { run: ({ parsedArgs }) => runPlatformBillingUsage(parsedArgs) },
  "platform billing spend-controls set": { run: ({ parsedArgs }) => runPlatformBillingSpendControlsSet(parsedArgs) },
  "platform billing topup": { run: ({ parsedArgs }) => runPlatformBillingTopup(parsedArgs) },
  "platform regent runtime": { run: ({ parsedArgs }) => runPlatformRegentRuntime(parsedArgs) },
  "platform regent pause": { run: ({ parsedArgs }) => runPlatformRegentPause(parsedArgs) },
  "platform regent resume": { run: ({ parsedArgs }) => runPlatformRegentResume(parsedArgs) },
  "service init": { run: ({ parsedArgs }) => runServiceInit(parsedArgs) },
  "service test": { run: ({ parsedArgs }) => runServiceTest(parsedArgs) },
  "service price set": { run: ({ parsedArgs }) => runServicePriceSet(parsedArgs) },
  "service publish": { run: ({ parsedArgs }) => runServicePublish(parsedArgs) },
  "service pause": { run: ({ parsedArgs }) => runServicePause(parsedArgs) },
  "service resume": { run: ({ parsedArgs }) => runServiceResume(parsedArgs) },
  "service runs": { run: ({ parsedArgs }) => runServiceRuns(parsedArgs) },
  "service logs": { run: ({ parsedArgs }) => runServiceLogs(parsedArgs) },
  "service catalog check": { run: ({ parsedArgs }) => runServiceCatalogCheck(parsedArgs) },
};
