import {
  runAutoskillInitEval,
  runAutoskillInitSkill,
  runAutoskillNotebookPair,
  runAutoskillBuy,
  runAutoskillListingCreate,
  runAutoskillPublishEval,
  runAutoskillPublishResult,
  runAutoskillPublishSkill,
  runAutoskillRefund,
  runAutoskillPull,
  runAutoskillReview,
} from "../commands/autoskill.js";
import {
  runTechtreeActivity,
  runTechtreeCommentAdd,
  runTechtreeInbox,
  runTechtreeNodeChildren,
  runTechtreeNodeComments,
  runTechtreeNodeGet,
  runTechtreeNodeCrossChainLinksCreate,
  runTechtreeNodeCrossChainLinksClear,
  runTechtreeNodeCrossChainLinksList,
  runTechtreeNodeLineageClaim,
  runTechtreeNodeLineageWithdraw,
  runTechtreeNodeLineageList,
  runTechtreeNodeWorkPacket,
  runTechtreeNodeCreate,
  runTechtreeNodesList,
  runTechtreeOpportunities,
  runTechtreeSearch,
  runTechtreeScienceRun,
  runTechtreeScienceSetGoal,
  runTechtreeStar,
  runTechtreeStatus,
  runTechtreeUnstar,
  runTechtreeUnwatch,
  runTechtreeScienceTasksChecklist,
  runTechtreeScienceTasksEvidence,
  runTechtreeScienceTasksExport,
  runTechtreeScienceTasksGet,
  runTechtreeScienceTasksInit,
  runTechtreeScienceTasksList,
  runTechtreeScienceTasksReviewLoop,
  runTechtreeScienceTasksReviewUpdate,
  runTechtreeScienceTasksSubmit,
  runTechtreeWorkAccept,
  runTechtreeWorkList,
  runTechtreeWorkNext,
  runTechtreeWorkPublish,
  runTechtreeWorkSummary,
  runTechtreeScienceAgentSet,
  runTechtreeNotebooksInit,
  runTechtreeNotebooksPair,
  runTechtreeNotebooksPublish,
  runTechtreeWatch,
  runTechtreeWatchList,
  runTechtreeWatchTail,
  runTechtreeBenchmarksCapsuleInit,
  runTechtreeBenchmarksCapsulePack,
  runTechtreeBenchmarksCapsuleSubmit,
  runTechtreeBenchmarksGet,
  runTechtreeBenchmarksList,
  runTechtreeBenchmarksReliability,
  runTechtreeBenchmarksRunMaterialize,
  runTechtreeBenchmarksRunRepeat,
  runTechtreeBenchmarksRunSubmit,
  runTechtreeBenchmarksScoreboard,
  runTechtreeBenchmarksValidate,
  runTechtreeRunbookAnswerAttachPaidSolution,
  runTechtreeRunbookAnswerPost,
  runTechtreeRunbookAnswerVote,
  runTechtreeRunbookInviteRequest,
  runTechtreeRunbookMarkSolved,
  runTechtreeRunbookPaymentAddressSet,
  runTechtreeRunbookQuestionPost,
  runTechtreeRunbookQuestionsGet,
  runTechtreeRunbookQuestionsList,
  runTechtreeRunbookUnlock,
  runTechtreeTechEpochCurrent,
  runTechtreeTechLeaderboardsConfirm,
  runTechtreeTechLeaderboardsList,
  runTechtreeTechLeaderboardsRegister,
  runTechtreeTechRewardsClaim,
  runTechtreeTechRewardsList,
  runTechtreeTechRewardsProof,
  runTechtreeTechRewardsRootConfirm,
  runTechtreeTechRewardsRootPrepare,
  runTechtreeTechStatus,
  runTechtreeTechWithdraw,
} from "../commands/techtree.js";
import {
  runTechtreeFoldPolicyInit,
  runTechtreeFoldProof,
  runTechtreeFoldReport,
  runTechtreeFoldStatus,
} from "../commands/techtree-fold.js";
import {
  runTechtreeIdentitiesList,
  runTechtreeIdentitiesMint,
} from "../commands/techtree-identities.js";
import { runTechtreeStartCommand } from "../commands/techtree-start.js";
import { runTechtreeSettlementVerify } from "../commands/techtree-settlement-verify.js";
import {
  runTechtreeBbhDraftApply,
  runTechtreeBbhDraftCreate,
  runTechtreeBbhDraftInit,
  runTechtreeBbhDraftList,
  runTechtreeBbhDraftProposals,
  runTechtreeBbhDraftPropose,
  runTechtreeBbhDraftPull,
  runTechtreeBbhDraftReady,
} from "../commands/techtree-v1-bbh-draft.js";
import {
  runTechtreeBbhGenomeImprove,
  runTechtreeBbhGenomeInit,
  runTechtreeBbhGenomePropose,
  runTechtreeBbhGenomeScore,
} from "../commands/techtree-v1-bbh-genome.js";
import { runTechtreeCertificateVerify } from "../commands/techtree-v1-certificate.js";
import {
  runTechtreeBbhRunExec,
  runTechtreeBbhNotebookPair,
  runTechtreeBbhRunSolve,
  runTechtreeBbhSubmit,
  runTechtreeBbhValidate,
  runTechtreeFetch,
  runTechtreeBbhCapsulesGet,
  runTechtreeBbhCapsulesList,
  runTechtreeBbhLeaderboard,
  runTechtreeBbhSync,
  runTechtreeVerify,
} from "../commands/techtree-v1.js";
import {
  runTechtreeReviewClaim,
  runTechtreeReviewList,
  runTechtreeReviewPull,
  runTechtreeReviewSubmit,
} from "../commands/techtree-v1-review.js";
import {
  runTechtreeReviewerApply,
  runTechtreeReviewerOrcidLink,
  runTechtreeReviewerStatus,
} from "../commands/techtree-v1-reviewer.js";
import { parsePositiveInteger } from "../parse.js";
import type { CliHandlerRegistry } from "./shared.js";

const requireNodeId = (value: string | undefined): number => {
  if (!value) {
    throw new Error("missing required node id");
  }

  return parsePositiveInteger(value, "invalid node id");
};

export const techtreeHandlers: CliHandlerRegistry = {
  "techtree status": { run: ({ configPath }) => runTechtreeStatus(configPath) },
  "techtree science-tasks list": { run: ({ parsedArgs, configPath }) => runTechtreeScienceTasksList(parsedArgs, configPath) },
  "techtree science-tasks get": { run: ({ parsedArgs, configPath }) => runTechtreeScienceTasksGet(parsedArgs, configPath), variadicTail: true },
  "techtree science-tasks init": { run: ({ parsedArgs, configPath }) => runTechtreeScienceTasksInit(parsedArgs, configPath) },
  "techtree science-tasks checklist": { run: ({ parsedArgs, configPath }) => runTechtreeScienceTasksChecklist(parsedArgs, configPath) },
  "techtree science-tasks evidence": { run: ({ parsedArgs, configPath }) => runTechtreeScienceTasksEvidence(parsedArgs, configPath) },
  "techtree science-tasks export": { run: ({ parsedArgs, configPath }) => runTechtreeScienceTasksExport(parsedArgs, configPath) },
  "techtree science-tasks submit": { run: ({ parsedArgs, configPath }) => runTechtreeScienceTasksSubmit(parsedArgs, configPath) },
  "techtree science-tasks review-update": { run: ({ parsedArgs, configPath }) => runTechtreeScienceTasksReviewUpdate(parsedArgs, configPath) },
  "techtree science-tasks review-loop": { run: ({ parsedArgs, configPath }) => runTechtreeScienceTasksReviewLoop(parsedArgs, configPath) },
  "techtree science set-goal": { run: ({ parsedArgs, configPath }) => runTechtreeScienceSetGoal(parsedArgs, configPath) },
  "techtree science agent set <agent>": { run: ({ parsedArgs, configPath }) => runTechtreeScienceAgentSet(parsedArgs, configPath) },
  "techtree science run": { run: ({ parsedArgs, configPath }) => runTechtreeScienceRun(parsedArgs, configPath) },
  "techtree work list": { run: ({ parsedArgs, configPath }) => runTechtreeWorkList(parsedArgs, configPath) },
  "techtree work next": { run: ({ parsedArgs, configPath }) => runTechtreeWorkNext(parsedArgs, configPath) },
  "techtree work accept": { run: ({ parsedArgs, configPath }) => runTechtreeWorkAccept(parsedArgs, configPath) },
  "techtree work publish": { run: ({ parsedArgs, configPath }) => runTechtreeWorkPublish(parsedArgs, configPath) },
  "techtree work": { run: ({ parsedArgs, configPath }) => runTechtreeWorkSummary(parsedArgs, configPath) },
  "techtree notebooks init": { run: ({ parsedArgs, configPath }) => runTechtreeNotebooksInit(parsedArgs, configPath) },
  "techtree notebooks pair": { run: ({ parsedArgs, configPath }) => runTechtreeNotebooksPair(parsedArgs, configPath) },
  "techtree notebooks publish": { run: ({ parsedArgs, configPath }) => runTechtreeNotebooksPublish(parsedArgs, configPath) },
  "techtree benchmarks list": { run: ({ parsedArgs, configPath }) => runTechtreeBenchmarksList(parsedArgs, configPath) },
  "techtree benchmarks get <capsule_id>": { run: ({ parsedArgs, configPath }) => runTechtreeBenchmarksGet(parsedArgs, configPath) },
  "techtree benchmarks scoreboard <capsule_id>": { run: ({ parsedArgs, configPath }) => runTechtreeBenchmarksScoreboard(parsedArgs, configPath) },
  "techtree benchmarks reliability <capsule_id>": { run: ({ parsedArgs, configPath }) => runTechtreeBenchmarksReliability(parsedArgs, configPath) },
  "techtree benchmarks capsule init": { run: ({ parsedArgs, configPath }) => runTechtreeBenchmarksCapsuleInit(parsedArgs, configPath) },
  "techtree benchmarks capsule pack": { run: ({ parsedArgs, configPath }) => runTechtreeBenchmarksCapsulePack(parsedArgs, configPath) },
  "techtree benchmarks capsule submit": { run: ({ parsedArgs, configPath }) => runTechtreeBenchmarksCapsuleSubmit(parsedArgs, configPath) },
  "techtree benchmarks run materialize": { run: ({ parsedArgs, configPath }) => runTechtreeBenchmarksRunMaterialize(parsedArgs, configPath) },
  "techtree benchmarks run submit": { run: ({ parsedArgs, configPath }) => runTechtreeBenchmarksRunSubmit(parsedArgs, configPath) },
  "techtree benchmarks run repeat": { run: ({ parsedArgs, configPath }) => runTechtreeBenchmarksRunRepeat(parsedArgs, configPath) },
  "techtree benchmarks validate": { run: ({ parsedArgs, configPath }) => runTechtreeBenchmarksValidate(parsedArgs, configPath) },
  "techtree fold policy init": { run: ({ parsedArgs, configPath }) => runTechtreeFoldPolicyInit(parsedArgs, configPath) },
  "techtree fold status": { run: ({ parsedArgs, configPath }) => runTechtreeFoldStatus(parsedArgs, configPath) },
  "techtree fold proof": { run: ({ parsedArgs, configPath }) => runTechtreeFoldProof(parsedArgs, configPath) },
  "techtree fold report": { run: ({ parsedArgs, configPath }) => runTechtreeFoldReport(parsedArgs, configPath) },
  "techtree runbook questions list": { run: ({ parsedArgs, configPath }) => runTechtreeRunbookQuestionsList(parsedArgs, configPath) },
  "techtree runbook questions get <id>": { run: ({ parsedArgs, configPath }) => runTechtreeRunbookQuestionsGet(parsedArgs, configPath) },
  "techtree runbook payment-address set": { run: ({ parsedArgs, configPath }) => runTechtreeRunbookPaymentAddressSet(parsedArgs, configPath) },
  "techtree runbook question post": { run: ({ parsedArgs, configPath }) => runTechtreeRunbookQuestionPost(parsedArgs, configPath) },
  "techtree runbook answer post <question_id>": { run: ({ parsedArgs, configPath }) => runTechtreeRunbookAnswerPost(parsedArgs, configPath) },
  "techtree runbook answer attach-paid-solution <answer_id>": { run: ({ parsedArgs, configPath }) => runTechtreeRunbookAnswerAttachPaidSolution(parsedArgs, configPath) },
  "techtree runbook answer vote <answer_id>": { run: ({ parsedArgs, configPath }) => runTechtreeRunbookAnswerVote(parsedArgs, configPath) },
  "techtree runbook mark-solved <question_id>": { run: ({ parsedArgs, configPath }) => runTechtreeRunbookMarkSolved(parsedArgs, configPath) },
  "techtree runbook unlock <answer_id>": { run: ({ parsedArgs, configPath }) => runTechtreeRunbookUnlock(parsedArgs, configPath) },
  "techtree runbook invite-request <question_id>": { run: ({ parsedArgs, configPath }) => runTechtreeRunbookInviteRequest(parsedArgs, configPath) },
  "techtree tech status": { run: ({ parsedArgs, configPath }) => runTechtreeTechStatus(parsedArgs, configPath) },
  "techtree tech epochs current": { run: ({ parsedArgs, configPath }) => runTechtreeTechEpochCurrent(parsedArgs, configPath) },
  "techtree tech leaderboards list": { run: ({ parsedArgs, configPath }) => runTechtreeTechLeaderboardsList(parsedArgs, configPath) },
  "techtree tech leaderboards register": { run: ({ parsedArgs, configPath }) => runTechtreeTechLeaderboardsRegister(parsedArgs, configPath) },
  "techtree tech leaderboards confirm": { run: ({ parsedArgs, configPath }) => runTechtreeTechLeaderboardsConfirm(parsedArgs, configPath) },
  "techtree tech rewards list": { run: ({ parsedArgs, configPath }) => runTechtreeTechRewardsList(parsedArgs, configPath) },
  "techtree tech rewards proof": { run: ({ parsedArgs, configPath }) => runTechtreeTechRewardsProof(parsedArgs, configPath) },
  "techtree tech rewards claim": { run: ({ parsedArgs, configPath }) => runTechtreeTechRewardsClaim(parsedArgs, configPath) },
  "techtree tech rewards root prepare": { run: ({ parsedArgs, configPath }) => runTechtreeTechRewardsRootPrepare(parsedArgs, configPath) },
  "techtree tech rewards root confirm": { run: ({ parsedArgs, configPath }) => runTechtreeTechRewardsRootConfirm(parsedArgs, configPath) },
  "techtree tech withdraw": { run: ({ parsedArgs, configPath }) => runTechtreeTechWithdraw(parsedArgs, configPath) },
  "techtree settlement verify": { run: ({ parsedArgs, configPath }) => runTechtreeSettlementVerify(parsedArgs, configPath) },
  // `techtree start` owns its exit code via runTechtreeStartCommand (mirrors top-level `start`).
  "techtree start": { run: ({ parsedArgs, configPath }) => runTechtreeStartCommand(parsedArgs, configPath) },
  "techtree autoskill init skill": { run: ({ parsedArgs, configPath }) => runAutoskillInitSkill(parsedArgs, configPath), variadicTail: true },
  "techtree autoskill init eval": { run: ({ parsedArgs, configPath }) => runAutoskillInitEval(parsedArgs, configPath), variadicTail: true },
  "techtree autoskill notebook pair": { run: ({ parsedArgs, configPath }) => runAutoskillNotebookPair(parsedArgs, configPath), variadicTail: true },
  "techtree autoskill publish skill": { run: ({ parsedArgs, configPath }) => runAutoskillPublishSkill(parsedArgs, configPath), variadicTail: true },
  "techtree autoskill publish eval": { run: ({ parsedArgs, configPath }) => runAutoskillPublishEval(parsedArgs, configPath), variadicTail: true },
  "techtree autoskill publish result": { run: ({ parsedArgs, configPath }) => runAutoskillPublishResult(parsedArgs, configPath), variadicTail: true },
  "techtree autoskill review": { run: ({ parsedArgs, configPath }) => runAutoskillReview(parsedArgs, configPath) },
  "techtree autoskill listing create": { run: ({ parsedArgs, configPath }) => runAutoskillListingCreate(parsedArgs, configPath) },
  "techtree autoskill buy": { run: ({ parsedArgs, configPath }) => runAutoskillBuy(parsedArgs, configPath), variadicTail: true },
  "techtree autoskill refund": { run: ({ parsedArgs, configPath }) => runAutoskillRefund(parsedArgs, configPath), variadicTail: true },
  "techtree autoskill pull": { run: ({ parsedArgs, configPath }) => runAutoskillPull(parsedArgs, configPath), variadicTail: true },
  "techtree reviewer orcid link": { run: ({ parsedArgs, configPath }) => runTechtreeReviewerOrcidLink(parsedArgs, configPath) },
  "techtree reviewer apply": { run: ({ parsedArgs, configPath }) => runTechtreeReviewerApply(parsedArgs, configPath) },
  "techtree reviewer status": { run: ({ configPath }) => runTechtreeReviewerStatus(configPath) },
  "techtree review list": { run: ({ parsedArgs, configPath }) => runTechtreeReviewList(parsedArgs, configPath) },
  "techtree review claim": { run: ({ parsedArgs, configPath }) => runTechtreeReviewClaim(parsedArgs, configPath), variadicTail: true },
  "techtree review pull": { run: ({ parsedArgs, configPath }) => runTechtreeReviewPull(parsedArgs, configPath), variadicTail: true },
  "techtree review submit": { run: ({ parsedArgs, configPath }) => runTechtreeReviewSubmit(parsedArgs, configPath), variadicTail: true },
  "techtree certificate verify": { run: ({ parsedArgs, configPath }) => runTechtreeCertificateVerify(parsedArgs, configPath), variadicTail: true },
  "techtree activity": { run: ({ parsedArgs, configPath }) => runTechtreeActivity(parsedArgs, configPath) },
  "techtree search": { run: ({ parsedArgs, configPath }) => runTechtreeSearch(parsedArgs, configPath) },
  "techtree nodes list": { run: ({ rawArgs, configPath }) => runTechtreeNodesList(rawArgs, configPath) },
  // Placeholder-bearing node commands read their numeric id from positionals by index.
  "techtree node get <id>": { run: ({ positionals, configPath }) => runTechtreeNodeGet(requireNodeId(positionals[3]), configPath) },
  "techtree node children <id>": { run: ({ rawArgs, positionals, configPath }) => runTechtreeNodeChildren(rawArgs, requireNodeId(positionals[3]), configPath) },
  "techtree node comments <id>": { run: ({ rawArgs, positionals, configPath }) => runTechtreeNodeComments(rawArgs, requireNodeId(positionals[3]), configPath) },
  "techtree node lineage list": { run: ({ parsedArgs, configPath }) => runTechtreeNodeLineageList(parsedArgs, configPath), variadicTail: true },
  "techtree node lineage claim": { run: ({ parsedArgs, configPath }) => runTechtreeNodeLineageClaim(parsedArgs, configPath), variadicTail: true },
  "techtree node lineage withdraw": { run: ({ parsedArgs, configPath }) => runTechtreeNodeLineageWithdraw(parsedArgs, configPath), variadicTail: true },
  "techtree node cross-chain-links list": { run: ({ parsedArgs, configPath }) => runTechtreeNodeCrossChainLinksList(parsedArgs, configPath), variadicTail: true },
  "techtree node cross-chain-links create": { run: ({ parsedArgs, configPath }) => runTechtreeNodeCrossChainLinksCreate(parsedArgs, configPath), variadicTail: true },
  "techtree node cross-chain-links clear": { run: ({ parsedArgs, configPath }) => runTechtreeNodeCrossChainLinksClear(parsedArgs, configPath), variadicTail: true },
  "techtree node create": { run: ({ rawArgs, configPath }) => runTechtreeNodeCreate(rawArgs, configPath) },
  "techtree comment add": { run: ({ rawArgs, configPath }) => runTechtreeCommentAdd(rawArgs, configPath) },
  "techtree node work-packet <id>": { run: ({ positionals, configPath }) => runTechtreeNodeWorkPacket(requireNodeId(positionals[3]), configPath) },
  "techtree identities list": { run: ({ parsedArgs }) => runTechtreeIdentitiesList(parsedArgs) },
  "techtree identities mint": { run: ({ parsedArgs }) => runTechtreeIdentitiesMint(parsedArgs) },
  "techtree watch list": { run: ({ configPath }) => runTechtreeWatchList(configPath) },
  "techtree watch tail": { run: ({ parsedArgs, configPath }) => runTechtreeWatchTail(parsedArgs, configPath) },
  "techtree watch <id>": { run: ({ positionals, configPath }) => runTechtreeWatch(requireNodeId(positionals[2]), configPath) },
  "techtree unwatch <id>": { run: ({ positionals, configPath }) => runTechtreeUnwatch(requireNodeId(positionals[2]), configPath) },
  "techtree star <id>": { run: ({ positionals, configPath }) => runTechtreeStar(requireNodeId(positionals[2]), configPath) },
  "techtree unstar <id>": { run: ({ positionals, configPath }) => runTechtreeUnstar(requireNodeId(positionals[2]), configPath) },
  "techtree inbox": { run: ({ rawArgs, configPath }) => runTechtreeInbox(rawArgs, configPath) },
  "techtree opportunities": { run: ({ rawArgs, configPath }) => runTechtreeOpportunities(rawArgs, configPath) },
  // Named-tree (bbh / main) commands.
  "techtree bbh run exec": { run: ({ parsedArgs, configPath }) => runTechtreeBbhRunExec(parsedArgs, configPath), variadicTail: true },
  "techtree bbh run solve": { run: ({ parsedArgs, configPath }) => runTechtreeBbhRunSolve(parsedArgs, configPath), variadicTail: true },
  "techtree bbh notebook pair": { run: ({ parsedArgs, configPath }) => runTechtreeBbhNotebookPair(parsedArgs, configPath), variadicTail: true },
  "techtree bbh capsules list": { run: ({ parsedArgs, configPath }) => runTechtreeBbhCapsulesList(parsedArgs, configPath) },
  "techtree bbh capsules get": { run: ({ parsedArgs, configPath }) => runTechtreeBbhCapsulesGet(parsedArgs, configPath), variadicTail: true },
  "techtree bbh submit": { run: ({ parsedArgs, configPath }) => runTechtreeBbhSubmit(parsedArgs, configPath) },
  "techtree bbh validate": { run: ({ parsedArgs, configPath }) => runTechtreeBbhValidate(parsedArgs, configPath) },
  "techtree bbh leaderboard": { run: ({ parsedArgs, configPath }) => runTechtreeBbhLeaderboard(parsedArgs, configPath) },
  "techtree bbh draft init": { run: ({ parsedArgs, configPath }) => runTechtreeBbhDraftInit(parsedArgs, configPath), variadicTail: true },
  "techtree bbh draft create": { run: ({ parsedArgs, configPath }) => runTechtreeBbhDraftCreate(parsedArgs, configPath), variadicTail: true },
  "techtree bbh draft list": { run: ({ configPath }) => runTechtreeBbhDraftList(configPath) },
  "techtree bbh draft pull": { run: ({ parsedArgs, configPath }) => runTechtreeBbhDraftPull(parsedArgs, configPath), variadicTail: true },
  "techtree bbh draft propose": { run: ({ parsedArgs, configPath }) => runTechtreeBbhDraftPropose(parsedArgs, configPath), variadicTail: true },
  "techtree bbh draft proposals": { run: ({ parsedArgs, configPath }) => runTechtreeBbhDraftProposals(parsedArgs, configPath) },
  "techtree bbh draft apply": { run: ({ parsedArgs, configPath }) => runTechtreeBbhDraftApply(parsedArgs, configPath), variadicTail: true },
  "techtree bbh draft ready": { run: ({ parsedArgs, configPath }) => runTechtreeBbhDraftReady(parsedArgs, configPath), variadicTail: true },
  "techtree bbh genome init": { run: ({ parsedArgs, configPath }) => runTechtreeBbhGenomeInit(parsedArgs, configPath), variadicTail: true },
  "techtree bbh genome score": { run: ({ parsedArgs, configPath }) => runTechtreeBbhGenomeScore(parsedArgs, configPath), variadicTail: true },
  "techtree bbh genome improve": { run: ({ parsedArgs, configPath }) => runTechtreeBbhGenomeImprove(parsedArgs, configPath), variadicTail: true },
  "techtree bbh genome propose": { run: ({ parsedArgs, configPath }) => runTechtreeBbhGenomePropose(parsedArgs, configPath), variadicTail: true },
  "techtree bbh sync": { run: ({ parsedArgs, configPath }) => runTechtreeBbhSync(parsedArgs, configPath) },
  // `main fetch`/`main verify` pass the tree name explicitly to the shared handler.
  "techtree main fetch": { run: ({ parsedArgs, configPath }) => runTechtreeFetch("main", parsedArgs, configPath), variadicTail: true },
  "techtree main verify": { run: ({ parsedArgs, configPath }) => runTechtreeVerify("main", parsedArgs, configPath), variadicTail: true },
};
