import {
  runXmtpDmList,
  runXmtpDmSend,
  runXmtpDoctor,
  runXmtpGroupAddMember,
  runXmtpGroupAddAdmin,
  runXmtpGroupAddSuperAdmin,
  runXmtpGroupAdmins,
  runXmtpGroupCreate,
  runXmtpGroupList,
  runXmtpGroupMembers,
  runXmtpGroupPermissions,
  runXmtpGroupRemoveAdmin,
  runXmtpGroupRemoveMember,
  runXmtpGroupRemoveSuperAdmin,
  runXmtpGroupSuperAdmins,
  runXmtpGroupUpdatePermission,
  runXmtpInbox,
  runXmtpInboxSync,
  runXmtpInit,
  runXmtpOwnerAdd,
  runXmtpOwnerList,
  runXmtpOwnerRemove,
  runXmtpPolicyEdit,
  runXmtpPolicyInit,
  runXmtpPolicyGet,
  runXmtpPolicyValidate,
  runXmtpRevokeOtherInstallations,
  runXmtpResolve,
  runXmtpRotateDbKey,
  runXmtpRotateWallet,
  runXmtpStatus,
  runXmtpTail,
  runXmtpTestDm,
  runXmtpTrustedAdd,
  runXmtpTrustedList,
  runXmtpTrustedRemove,
} from "../commands/xmtp.js";
import type { CliHandlerRegistry } from "./shared.js";

export const xmtpHandlers: CliHandlerRegistry = {
  "xmtp init": { run: ({ parsedArgs, configPath }) => runXmtpInit(parsedArgs, configPath) },
  "xmtp status": { run: ({ configPath }) => runXmtpStatus(configPath) },
  "xmtp resolve": { run: ({ parsedArgs, configPath }) => runXmtpResolve(parsedArgs, configPath) },
  "xmtp owner add": { run: ({ parsedArgs, configPath }) => runXmtpOwnerAdd(parsedArgs, configPath) },
  "xmtp owner list": { run: ({ configPath }) => runXmtpOwnerList(configPath) },
  "xmtp owner remove": { run: ({ parsedArgs, configPath }) => runXmtpOwnerRemove(parsedArgs, configPath) },
  "xmtp trusted add": { run: ({ parsedArgs, configPath }) => runXmtpTrustedAdd(parsedArgs, configPath) },
  "xmtp trusted list": { run: ({ configPath }) => runXmtpTrustedList(configPath) },
  "xmtp trusted remove": { run: ({ parsedArgs, configPath }) => runXmtpTrustedRemove(parsedArgs, configPath) },
  "xmtp policy init": { run: ({ configPath }) => runXmtpPolicyInit(configPath) },
  "xmtp policy get": { run: ({ configPath }) => runXmtpPolicyGet(configPath) },
  "xmtp policy validate": { run: ({ configPath }) => runXmtpPolicyValidate(configPath) },
  "xmtp policy edit": { run: ({ configPath }) => runXmtpPolicyEdit(configPath) },
  "xmtp test dm": { run: ({ parsedArgs, configPath }) => runXmtpTestDm(parsedArgs, configPath) },
  "xmtp dm send": { run: ({ parsedArgs, configPath }) => runXmtpDmSend(parsedArgs, configPath) },
  "xmtp dm list": { run: ({ parsedArgs, configPath }) => runXmtpDmList(parsedArgs, configPath) },
  "xmtp inbox": { run: ({ parsedArgs, configPath }) => runXmtpInbox(parsedArgs, configPath) },
  "xmtp inbox sync": { run: ({ configPath }) => runXmtpInboxSync(configPath) },
  "xmtp tail": { run: ({ parsedArgs, configPath }) => runXmtpTail(parsedArgs, configPath) },
  "xmtp group create": { run: ({ parsedArgs, configPath }) => runXmtpGroupCreate(parsedArgs, configPath), variadicTail: true },
  "xmtp group add-member": { run: ({ parsedArgs, configPath }) => runXmtpGroupAddMember(parsedArgs, configPath), variadicTail: true },
  "xmtp group remove-member": { run: ({ parsedArgs, configPath }) => runXmtpGroupRemoveMember(parsedArgs, configPath), variadicTail: true },
  "xmtp group list": { run: ({ parsedArgs, configPath }) => runXmtpGroupList(parsedArgs, configPath) },
  "xmtp group members": { run: ({ parsedArgs, configPath }) => runXmtpGroupMembers(parsedArgs, configPath), variadicTail: true },
  "xmtp group permissions": { run: ({ parsedArgs, configPath }) => runXmtpGroupPermissions(parsedArgs, configPath), variadicTail: true },
  "xmtp group update-permission": { run: ({ parsedArgs, configPath }) => runXmtpGroupUpdatePermission(parsedArgs, configPath), variadicTail: true },
  "xmtp group admins": { run: ({ parsedArgs, configPath }) => runXmtpGroupAdmins(parsedArgs, configPath), variadicTail: true },
  "xmtp group super-admins": { run: ({ parsedArgs, configPath }) => runXmtpGroupSuperAdmins(parsedArgs, configPath), variadicTail: true },
  "xmtp group add-admin": { run: ({ parsedArgs, configPath }) => runXmtpGroupAddAdmin(parsedArgs, configPath), variadicTail: true },
  "xmtp group remove-admin": { run: ({ parsedArgs, configPath }) => runXmtpGroupRemoveAdmin(parsedArgs, configPath), variadicTail: true },
  "xmtp group add-super-admin": { run: ({ parsedArgs, configPath }) => runXmtpGroupAddSuperAdmin(parsedArgs, configPath), variadicTail: true },
  "xmtp group remove-super-admin": { run: ({ parsedArgs, configPath }) => runXmtpGroupRemoveSuperAdmin(parsedArgs, configPath), variadicTail: true },
  "xmtp revoke-other-installations": { run: ({ configPath }) => runXmtpRevokeOtherInstallations(configPath) },
  "xmtp rotate-db-key": { run: ({ configPath }) => runXmtpRotateDbKey(configPath) },
  "xmtp rotate-wallet": { run: ({ configPath }) => runXmtpRotateWallet(configPath) },
  "xmtp doctor": { run: ({ parsedArgs, configPath }) => runXmtpDoctor(parsedArgs, configPath) },
};
