"""Regenerate each engine bundle's project file, lock and descriptor, and print its digest.

`uv lock` runs here and never on a participant's machine: their install is `uv sync --frozen`
against this lock, which is what makes two participants' engines the same engine. Every byte
written is a function of the constants below and the bundle's authored files.
"""

from __future__ import annotations

import subprocess
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Final

from regents_cli.techtree.canonical import digest_object
from regents_cli.techtree.engines.bundle import (
    DESCRIPTOR_FILENAME,
    PACKAGE_MANIFEST_SCHEMA,
    PACKAGES_DIRECTORY,
    SHIPPED_ENGINES,
    content_manifest,
    engine_bundle_digest,
    enumerate_bundle_files,
)
from regents_cli.techtree.fs import atomic_write_json, atomic_write_text
from regents_cli.techtree.models.base import Digest
from regents_cli.techtree.models.engine import EngineDescriptor, EnginePackage

ROOT: Final = Path(__file__).resolve().parents[2]
ENGINES_ROOT: Final = ROOT / "src/regents_cli/techtree/resources/engines"

#: An exact commit, never a branch, tag or range.
VERIFIERS_REPOSITORY: Final = "https://github.com/PrimeIntellect-ai/verifiers"
VERIFIERS_REVISION: Final = "fc73e02ea99594407bf7579c53f7711f7434635a"
PYTHON_SERIES: Final = "3.12"


@dataclass(frozen=True)
class Engine:
    """One Climb's engine: its taskset package, whose name is also its Verifiers taskset id."""

    name: str
    package: str
    description: str
    #: Verifiers extras the taskset needs, such as `harbor` for tasks graded in their own box.
    verifiers_extras: tuple[str, ...] = ()

    @property
    def verifiers_requirement(self) -> str:
        return (
            f"verifiers[{','.join(self.verifiers_extras)}]"
            if self.verifiers_extras
            else "verifiers"
        )


ENGINES: Final = (
    Engine(
        name="default",
        package="procedure-transfer-v1",
        description="Pinned Verifiers environment and reference tasksets for Techtree.",
    ),
    Engine(
        name="frontier-cs",
        package="frontier-cs-open-ended-v1",
        description="Pinned Verifiers environment and the Frontier-CS Open-Ended taskset for "
        "Techtree.",
    ),
    Engine(
        name="tasksmith",
        package="hf-tasksmith-v1",
        description="Pinned Verifiers environment and the HF Tasksmith taskset for Techtree.",
        verifiers_extras=("harbor",),
    ),
)


def project(engine: Engine) -> str:
    """The engine's generated project file."""
    return f"""\
# The managed Techtree evaluation engine.
#
# Generated by regents-cli's scripts/techtree/build_engine_bundle.py. Do not edit by hand:
# the file is part of the engine bundle digest.

[project]
name = "techtree-engine-{engine.name}"
version = "0.1.0"
description = "{engine.description}"
requires-python = ">=3.12,<3.13"
dependencies = [
  "{engine.package}",
  "{engine.verifiers_requirement}",
]

[tool.uv]
# The engine project is an environment, not a distribution. Nothing installs it.
package = false

[tool.uv.sources]
{engine.package} = {{ path = "{PACKAGES_DIRECTORY}/{engine.package}", editable = true }}
verifiers = {{ git = "{VERIFIERS_REPOSITORY}", rev = "{VERIFIERS_REVISION}" }}
"""


def package_source_digest(package_root: Path) -> Digest:
    """The digest of one shipped package's source tree, as the Campaign and TasksetLock name it."""
    return digest_object(
        content_manifest(PACKAGE_MANIFEST_SCHEMA, enumerate_bundle_files(package_root))
    )


def locked_verifiers_version(engine_root: Path) -> str:
    """The Verifiers version `uv lock` resolved at the pinned commit."""
    lock = tomllib.loads((engine_root / "uv.lock").read_text(encoding="utf-8"))
    return next(str(entry["version"]) for entry in lock["package"] if entry["name"] == "verifiers")


def build(engine: Engine) -> str:
    """Write one engine's project file, lock it, write its descriptor, and return its digest."""
    engine_root = ENGINES_ROOT / engine.name
    atomic_write_text(engine_root / "pyproject.toml", project(engine), mode=0o644)
    subprocess.run(
        ["uv", "lock", "--project", str(engine_root)], check=True, stdin=subprocess.DEVNULL
    )
    package_root = engine_root / PACKAGES_DIRECTORY / engine.package
    package = tomllib.loads((package_root / "pyproject.toml").read_text(encoding="utf-8"))
    descriptor = EngineDescriptor(
        schema_version="techtree.engine.v1alpha1",
        name=engine.name,
        python_version=PYTHON_SERIES,
        verifiers_version=locked_verifiers_version(engine_root),
        verifiers_revision=VERIFIERS_REVISION,
        supported_hosts=["darwin/amd64", "darwin/arm64", "linux/amd64", "linux/arm64"],
        packages=[
            EnginePackage(
                name=engine.package,
                version=package["project"]["version"],
                source_digest=package_source_digest(package_root),
            )
        ],
    )
    atomic_write_json(engine_root / DESCRIPTOR_FILENAME, descriptor, mode=0o644)
    return engine_bundle_digest(engine_root)


def main() -> None:
    """Build every engine the CLI ships and print each one's name and digest."""
    if tuple(engine.name for engine in ENGINES) != SHIPPED_ENGINES:
        raise SystemExit(f"this script builds {ENGINES}, but the CLI ships {SHIPPED_ENGINES}")
    for engine in ENGINES:
        sys.stdout.write(f"{engine.name} {build(engine)}\n")


if __name__ == "__main__":
    main()
