"""Regenerate the engine bundle's project file, lock and descriptor, and print its digest.

`uv lock` runs here and never on a participant's machine: their install is `uv sync --frozen`
against this lock, which is what makes two participants' engines the same engine. Every byte
written is a function of the constants below and the bundle's authored files.
"""

from __future__ import annotations

import subprocess
import sys
import tomllib
from pathlib import Path
from typing import Final

from regents_cli.techtree.canonical import digest_object
from regents_cli.techtree.engines.bundle import (
    DESCRIPTOR_FILENAME,
    PACKAGE_MANIFEST_SCHEMA,
    PACKAGES_DIRECTORY,
    content_manifest,
    engine_bundle_digest,
    enumerate_bundle_files,
)
from regents_cli.techtree.fs import atomic_write_json, atomic_write_text
from regents_cli.techtree.models.base import Digest
from regents_cli.techtree.models.engine import EngineDescriptor, EnginePackage

ROOT: Final = Path(__file__).resolve().parents[2]
ENGINE_ROOT: Final = ROOT / "src/regents_cli/techtree/resources/engines/default"

#: An exact commit, never a branch, tag or range.
VERIFIERS_REPOSITORY: Final = "https://github.com/PrimeIntellect-ai/verifiers"
VERIFIERS_REVISION: Final = "fc73e02ea99594407bf7579c53f7711f7434635a"
#: The reference taskset; its distribution name is also its Verifiers taskset id.
REFERENCE_PACKAGE: Final = "procedure-transfer-v1"
PYTHON_SERIES: Final = "3.12"

PROJECT: Final = f"""\
# The managed Techtree evaluation engine.
#
# Generated by regents-cli's scripts/techtree/build_engine_bundle.py. Do not edit by hand:
# the file is part of the engine bundle digest.

[project]
name = "techtree-engine-default"
version = "0.1.0"
description = "Pinned Verifiers environment and reference tasksets for Techtree."
requires-python = ">=3.12,<3.13"
dependencies = [
  "{REFERENCE_PACKAGE}",
  "verifiers",
]

[tool.uv]
# The engine project is an environment, not a distribution. Nothing installs it.
package = false

[tool.uv.sources]
{REFERENCE_PACKAGE} = {{ path = "{PACKAGES_DIRECTORY}/{REFERENCE_PACKAGE}", editable = true }}
verifiers = {{ git = "{VERIFIERS_REPOSITORY}", rev = "{VERIFIERS_REVISION}" }}
"""


def package_source_digest(package_root: Path) -> Digest:
    """The digest of one shipped package's source tree, as the Campaign and TasksetLock name it."""
    return digest_object(
        content_manifest(PACKAGE_MANIFEST_SCHEMA, enumerate_bundle_files(package_root))
    )


def locked_verifiers_version() -> str:
    """The Verifiers version `uv lock` resolved at the pinned commit."""
    lock = tomllib.loads((ENGINE_ROOT / "uv.lock").read_text(encoding="utf-8"))
    return next(str(entry["version"]) for entry in lock["package"] if entry["name"] == "verifiers")


def main() -> None:
    """Write the project file, lock it, write the descriptor, and print the bundle digest."""
    atomic_write_text(ENGINE_ROOT / "pyproject.toml", PROJECT, mode=0o644)
    subprocess.run(
        ["uv", "lock", "--project", str(ENGINE_ROOT)], check=True, stdin=subprocess.DEVNULL
    )
    package_root = ENGINE_ROOT / PACKAGES_DIRECTORY / REFERENCE_PACKAGE
    package = tomllib.loads((package_root / "pyproject.toml").read_text(encoding="utf-8"))
    descriptor = EngineDescriptor(
        schema_version="techtree.engine.v1alpha1",
        name="default",
        python_version=PYTHON_SERIES,
        verifiers_version=locked_verifiers_version(),
        verifiers_revision=VERIFIERS_REVISION,
        supported_hosts=["darwin/amd64", "darwin/arm64", "linux/amd64", "linux/arm64"],
        packages=[
            EnginePackage(
                name=REFERENCE_PACKAGE,
                version=package["project"]["version"],
                source_digest=package_source_digest(package_root),
            )
        ],
    )
    atomic_write_json(ENGINE_ROOT / DESCRIPTOR_FILENAME, descriptor, mode=0o644)
    sys.stdout.write(f"{engine_bundle_digest(ENGINE_ROOT)}\n")


if __name__ == "__main__":
    main()
