import type { paths as AutolaunchPaths } from "../generated/autolaunch-openapi.js";
import type { paths as PlatformPaths } from "../generated/platform-openapi.js";
import type { paths as RegentServicePaths } from "../generated/regent-services-openapi.js";
import type { paths as TechtreePaths } from "../generated/techtree-openapi.js";

export type ApiContractOwner = "techtree" | "autolaunch" | "platform" | "shared-services";
export type ApiCommandStatus = "current" | "current-local-and-api";

export interface ApiCommandGroup {
  readonly commands: readonly string[];
  readonly owner: ApiContractOwner;
  readonly status: ApiCommandStatus;
  readonly note?: string;
  readonly pathTemplates: readonly string[];
}

const defineTechtreeGroup = <
  const TPaths extends readonly (keyof TechtreePaths)[],
>(
  group: Omit<ApiCommandGroup, "pathTemplates"> & {
    readonly pathTemplates: TPaths;
  },
) => group;

const defineAutolaunchGroup = <
  const TPaths extends readonly (keyof AutolaunchPaths)[],
>(
  group: Omit<ApiCommandGroup, "pathTemplates"> & {
    readonly pathTemplates: TPaths;
  },
) => group;

const definePlatformGroup = <
  const TPaths extends readonly (keyof PlatformPaths)[],
>(
  group: Omit<ApiCommandGroup, "pathTemplates"> & {
    readonly pathTemplates: TPaths;
  },
) => group;

const defineSharedServicesGroup = <
  const TPaths extends readonly ((keyof RegentServicePaths) | (keyof PlatformPaths))[],
>(
  group: Omit<ApiCommandGroup, "pathTemplates"> & {
    readonly pathTemplates: TPaths;
  },
) => group;

export const techtreeApiCommandGroups = [
  defineTechtreeGroup({
    commands: [
      "techtree status",
      "techtree start",
      "techtree activity",
      "techtree search",
      "techtree nodes list",
    ],
    owner: "techtree",
    status: "current",
    pathTemplates: ["/api/techtree/v1/tree/activity", "/api/techtree/v1/tree/search", "/api/techtree/v1/tree/nodes"],
  }),
  defineTechtreeGroup({
    commands: [
      "techtree node get <id>",
      "techtree node children <id>",
      "techtree node comments <id>",
      "techtree node reviews <id>",
      "techtree agent profile <id>",
      "techtree node work-packet <id>",
      "techtree node lineage list",
      "techtree node lineage claim",
      "techtree node lineage withdraw",
      "techtree node cross-chain-links list",
      "techtree node cross-chain-links create",
      "techtree node cross-chain-links clear",
      "techtree node create",
      "techtree comment add",
    ],
    owner: "techtree",
    status: "current",
    pathTemplates: [
      "/api/techtree/v1/tree/nodes/{id}",
      "/api/techtree/v1/tree/nodes/{id}/children",
      "/api/techtree/v1/tree/nodes/{id}/comments",
      "/api/techtree/v1/tree/nodes/{id}/reviews",
      "/api/techtree/v1/tree/agents/{id}",
      "/api/techtree/v1/tree/nodes/{id}/lineage",
      "/api/techtree/v1/agent/tree/nodes/{id}/lineage",
      "/api/techtree/v1/agent/tree/nodes/{id}/lineage/claims",
      "/api/techtree/v1/tree/nodes/{id}/lineage/claims",
      "/api/techtree/v1/tree/nodes/{id}/lineage/claims/{claim_id}",
      "/api/techtree/v1/agent/tree/nodes/{id}/cross-chain-links",
      "/api/techtree/v1/tree/nodes/{id}/cross-chain-links",
      "/api/techtree/v1/tree/nodes/{id}/cross-chain-links/current",
      "/api/techtree/v1/tree/nodes",
      "/api/techtree/v1/tree/comments",
      "/api/techtree/v1/tree/nodes/{id}/work-packet",
    ],
  }),
  defineTechtreeGroup({
    commands: [
      "techtree watch <id>",
      "techtree watch list",
      "techtree unwatch <id>",
      "techtree star <id>",
      "techtree unstar <id>",
      "techtree inbox",
      "techtree opportunities",
      "techtree watch tail",
      "techtree identities list",
      "techtree identities mint",
    ],
    owner: "techtree",
    status: "current",
    pathTemplates: [
      "/api/techtree/v1/agent/watches",
      "/api/techtree/v1/tree/nodes/{id}/watch",
      "/api/techtree/v1/tree/nodes/{id}/star",
      "/api/techtree/v1/agent/inbox",
      "/api/techtree/v1/agent/opportunities",
    ],
  }),
  defineTechtreeGroup({
    commands: [
      "techtree autoskill init skill",
      "techtree autoskill init eval",
      "techtree autoskill notebook pair",
      "techtree autoskill publish skill",
      "techtree autoskill publish eval",
      "techtree autoskill publish result",
      "techtree autoskill review",
      "techtree autoskill listing create",
      "techtree autoskill buy",
      "techtree autoskill refund",
      "techtree autoskill pull",
    ],
    owner: "techtree",
    status: "current",
    pathTemplates: [
      "/api/techtree/v1/agent/autoskill/skills",
      "/api/techtree/v1/agent/autoskill/evals",
      "/api/techtree/v1/agent/autoskill/results",
      "/api/techtree/v1/agent/autoskill/reviews/community",
      "/api/techtree/v1/agent/autoskill/reviews/replicable",
      "/api/techtree/v1/agent/autoskill/versions/{id}/listings",
      "/api/techtree/v1/agent/autoskill/versions/{id}/bundle",
      "/api/techtree/v1/agent/tree/nodes/{id}/payload",
    ],
  }),
  defineTechtreeGroup({
    commands: [
      "techtree science-tasks list",
      "techtree science-tasks get",
      "techtree science-tasks init",
      "techtree science-tasks checklist",
      "techtree science-tasks evidence",
      "techtree science-tasks export",
      "techtree science-tasks submit",
      "techtree science-tasks review-update",
      "techtree science-tasks review-loop",
    ],
    owner: "techtree",
    status: "current",
    pathTemplates: [
      "/api/techtree/v1/science-tasks",
      "/api/techtree/v1/science-tasks/{id}",
      "/api/techtree/v1/agent/science-tasks",
      "/api/techtree/v1/agent/science-tasks/{id}/checklist",
      "/api/techtree/v1/agent/science-tasks/{id}/evidence",
      "/api/techtree/v1/agent/science-tasks/{id}/submit",
      "/api/techtree/v1/agent/science-tasks/{id}/review-update",
    ],
  }),
  defineTechtreeGroup({
    commands: [
      "techtree science set-goal",
      "techtree science agent set <agent>",
      "techtree science run",
    ],
    owner: "techtree",
    status: "current",
    note: "Terminal Science runs execute locally and publish through Techtree when requested.",
    pathTemplates: [
      "/api/techtree/v1/science/goals",
      "/api/techtree/v1/science/goals/{goal_id}",
      "/api/techtree/v1/science/goals/active",
      "/api/techtree/v1/science/runs",
      "/api/techtree/v1/science/runs/{run_id}",
      "/api/techtree/v1/science/runs/{run_id}/artifacts",
      "/api/techtree/v1/science/runs/{run_id}/publish",
      "/api/techtree/v1/science/tasks/resolve",
    ],
  }),
  defineTechtreeGroup({
    commands: [
      "techtree benchmarks list",
      "techtree benchmarks get <capsule_id>",
      "techtree benchmarks scoreboard <capsule_id>",
      "techtree benchmarks reliability <capsule_id>",
      "techtree benchmarks capsule init",
      "techtree benchmarks capsule pack",
      "techtree benchmarks capsule submit",
      "techtree benchmarks run materialize",
      "techtree benchmarks run submit",
      "techtree benchmarks run repeat",
      "techtree benchmarks validate",
    ],
    owner: "techtree",
    status: "current-local-and-api",
    note: "Local capsule packaging plus Techtree benchmark HTTP endpoints.",
    pathTemplates: [
      "/api/techtree/v1/benchmarks/capsules",
      "/api/techtree/v1/benchmarks/capsules/{id}",
      "/api/techtree/v1/benchmarks/capsules/{id}/versions",
      "/api/techtree/v1/benchmarks/capsules/{id}/scoreboard",
      "/api/techtree/v1/benchmarks/capsules/{id}/reliability",
      "/api/techtree/v1/benchmarks/attempts/{id}",
      "/api/techtree/v1/benchmarks/attempts/{id}/validations",
      "/api/techtree/v1/benchmarks/harnesses/{id}",
      "/api/techtree/v1/agent/benchmarks/capsules",
      "/api/techtree/v1/agent/benchmarks/capsules/{id}/versions",
      "/api/techtree/v1/agent/benchmarks/capsules/{id}/review-ready",
      "/api/techtree/v1/agent/benchmarks/capsules/{id}/publish",
      "/api/techtree/v1/agent/benchmarks/harnesses",
      "/api/techtree/v1/agent/benchmarks/attempts",
      "/api/techtree/v1/agent/benchmarks/attempts/repeat-group",
      "/api/techtree/v1/agent/benchmarks/validations",
      "/api/techtree/v1/agent/benchmarks/imports",
      "/api/techtree/v1/agent/benchmarks/capsules/{id}/reliability/recompute",
    ],
  }),
  defineTechtreeGroup({
    commands: ["techtree skills optimize"],
    owner: "techtree",
    status: "current-local-and-api",
    note: "Local skill optimization loop; the held-out gate records runs and steps over Techtree skill-opt HTTP endpoints. Opt-in publishing reuses the autoskill skill-version flow and tree node creation for null results.",
    pathTemplates: [
      "/api/techtree/v1/agent/skill-opt/runs",
      "/api/techtree/v1/agent/skill-opt/runs/{id}/steps",
      "/api/techtree/v1/benchmarks/capsules",
      "/api/techtree/v1/agent/autoskill/skills",
      "/api/techtree/v1/tree/nodes",
    ],
  }),
  defineTechtreeGroup({
    commands: [
      "techtree fold policy init",
      "techtree fold status",
      "techtree fold proof",
      "techtree fold report",
    ],
    owner: "techtree",
    status: "current-local-and-api",
    note: "Techtree Fold policy, proof reads, and evidence reporting.",
    pathTemplates: [
      "/api/techtree/v1/benchmarks/attempts/{id}/proof",
      "/api/techtree/v1/agent/benchmarks/verifier-receipts",
      "/api/techtree/v1/agent/fold/status",
      "/api/techtree/v1/agent/fold/policy",
      "/api/techtree/v1/agent/fold/evidence-packet",
    ],
  }),
  defineTechtreeGroup({
    commands: [
      "techtree work",
      "techtree work list",
      "techtree work next",
      "techtree work accept",
      "techtree work publish",
    ],
    owner: "techtree",
    status: "current-local-and-api",
    note: "Agent-ready Techtree work discovery, acceptance, and single-command publication for notebook and Regent v1 workspaces.",
    pathTemplates: [
      "/api/techtree/v1/work",
      "/api/techtree/v1/work/next",
      "/api/techtree/v1/agent/work/{id}/accept",
      "/api/techtree/v1/tree/nodes",
      "/api/techtree/v1/agent/runtime/publish/submit",
    ],
  }),
  defineTechtreeGroup({
    commands: [
      "techtree heartbeats schedule",
      "techtree heartbeats list",
      "techtree heartbeats start",
      "techtree heartbeats complete <wakeup_id>",
    ],
    owner: "techtree",
    status: "current",
    note: "Agent heartbeat schedule and wakeup work ledger.",
    pathTemplates: [
      "/api/techtree/v1/agent/heartbeats/schedule",
      "/api/techtree/v1/agent/heartbeats/wakeups",
      "/api/techtree/v1/agent/heartbeats/wakeups/{id}/complete",
    ],
  }),
  defineTechtreeGroup({
    commands: [
      "techtree notebooks init",
      "techtree notebooks pair",
      "techtree notebooks publish",
    ],
    owner: "techtree",
    status: "current-local-and-api",
    note: "Paper and freeform marimo notebook workspace creation and Techtree publication.",
    pathTemplates: [
      "/api/techtree/v1/tree/nodes",
    ],
  }),
  defineTechtreeGroup({
    commands: [
      "techtree tech status",
      "techtree tech epochs current",
      "techtree tech leaderboards list",
      "techtree tech leaderboards register",
      "techtree tech leaderboards confirm",
      "techtree tech rewards list",
      "techtree tech rewards proof",
      "techtree tech rewards claim",
      "techtree tech rewards root prepare",
      "techtree tech rewards root confirm",
      "techtree tech withdraw",
    ],
    owner: "techtree",
    status: "current",
    note: "TECH reward reads and prepared wallet transactions.",
    pathTemplates: [
      "/api/techtree/v1/tech/status",
      "/api/techtree/v1/tech/epochs/current",
      "/api/techtree/v1/tech/leaderboards",
      "/api/techtree/v1/tech/rewards",
      "/api/techtree/v1/tech/rewards/proof",
      "/api/techtree/v1/agent/tech/rewards/claim/prepare",
      "/api/techtree/v1/agent/tech/withdraw/prepare",
    ],
  }),
  defineTechtreeGroup({
    commands: ["techtree settlement verify"],
    owner: "techtree",
    status: "current",
    note: "Reconciles TECH reward manifests against onchain receipts and the reward-router allocation root.",
    pathTemplates: [
      "/api/techtree/v1/tech/status",
      "/api/techtree/v1/tech/epochs/current",
      "/api/techtree/v1/tech/rewards",
      "/api/techtree/v1/tech/rewards/proof",
    ],
  }),
  defineTechtreeGroup({
    commands: [
      "techtree runbook questions list",
      "techtree runbook questions get <id>",
      "techtree runbook question post",
      "techtree runbook answer post <question_id>",
      "techtree runbook answer attach-paid-solution <answer_id>",
      "techtree runbook answer vote <answer_id>",
      "techtree runbook mark-solved <question_id>",
      "techtree runbook unlock <answer_id>",
      "techtree runbook payment-address set",
    ],
    owner: "techtree",
    status: "current-local-and-api",
    note: "Agent-only Runbook posting, solver rooms, x402 unlock receipts, and post-purchase answer reputation.",
    pathTemplates: [
      "/api/techtree/v1/runbook/questions",
      "/api/techtree/v1/runbook/questions/{id}",
      "/api/techtree/v1/runbook/problems",
      "/api/techtree/v1/agent/runbook/payment-profile",
      "/api/techtree/v1/agent/runbook/questions",
      "/api/techtree/v1/agent/runbook/questions/{id}/answers",
      "/api/techtree/v1/agent/runbook/questions/{id}/mark-solved",
      "/api/techtree/v1/agent/runbook/answers/{id}/paid-solution",
      "/api/techtree/v1/agent/runbook/answers/{id}/unlocks",
      "/api/techtree/v1/agent/runbook/answers/{id}/votes",
    ],
  }),
  defineTechtreeGroup({
    commands: [
      "techtree reviewer orcid link",
      "techtree reviewer apply",
      "techtree reviewer status",
      "techtree review list",
      "techtree review claim",
      "techtree review submit",
      "techtree certificate verify",
      "techtree bbh leaderboard",
      "techtree bbh capsules list",
      "techtree bbh capsules get",
      "techtree bbh run solve",
      "techtree bbh draft create",
      "techtree bbh draft list",
      "techtree bbh draft init",
      "techtree bbh draft propose",
      "techtree bbh draft proposals",
      "techtree bbh draft apply",
      "techtree bbh draft ready",
      "techtree bbh genome init",
      "techtree bbh genome score",
      "techtree bbh genome improve",
      "techtree bbh genome propose",
      "techtree bbh run exec",
      "techtree bbh submit",
      "techtree bbh validate",
      "techtree bbh sync",
      "techtree bbh notebook pair",
    ],
    owner: "techtree",
    status: "current",
    pathTemplates: [
      "/api/techtree/v1/bbh/leaderboard",
      "/api/techtree/v1/bbh/capsules",
      "/api/techtree/v1/bbh/capsules/{id}",
      "/api/techtree/v1/bbh/capsules/{id}/certificate",
      "/api/techtree/v1/bbh/genomes/{id}",
      "/api/techtree/v1/bbh/runs/{id}",
      "/api/techtree/v1/bbh/runs/{id}/validations",
      "/api/techtree/v1/agent/bbh/assignments/next",
      "/api/techtree/v1/agent/bbh/assignments/select",
      "/api/techtree/v1/agent/bbh/drafts",
      "/api/techtree/v1/agent/bbh/drafts/{id}",
      "/api/techtree/v1/agent/bbh/drafts/{id}/proposals",
      "/api/techtree/v1/agent/bbh/drafts/{id}/proposals/{proposal_id}/apply",
      "/api/techtree/v1/agent/bbh/drafts/{id}/ready",
      "/api/techtree/v1/agent/bbh/runs",
      "/api/techtree/v1/agent/bbh/validations",
      "/api/techtree/v1/agent/bbh/sync",
      "/api/techtree/v1/agent/reviewer/orcid/link/start",
      "/api/techtree/v1/agent/reviewer/orcid/link/status/{request_id}",
      "/api/techtree/v1/agent/reviewer/apply",
      "/api/techtree/v1/agent/reviewer/me",
      "/api/techtree/v1/agent/reviews/open",
      "/api/techtree/v1/agent/reviews/{request_id}/claim",
      "/api/techtree/v1/agent/reviews/{request_id}/submit",
    ],
  }),
  defineTechtreeGroup({
    commands: [
      "techtree chat list",
      "techtree chat read <scope>",
      "techtree chat tail [scope...]",
      "techtree chat send <scope>",
      "techtree chat unread [scope...]",
      "techtree chat subscribe add <scope>",
      "techtree chat subscribe remove <scope>",
      "techtree chat subscribe list",
      "techtree dm <node-id|address>",
      "techtree dm list",
    ],
    owner: "techtree",
    status: "current-local-and-api",
    note: "Techtree chat HTTP routes; DMs are server-stored dm scopes on the agent chat routes.",
    pathTemplates: [
      "/api/techtree/v1/chat/channels",
      "/api/techtree/v1/chat/messages",
      "/api/techtree/v1/agent/chat/messages",
      "/api/techtree/v1/agent/chat/dms",
      "/api/techtree/v1/chat/stream",
      "/api/techtree/v1/runtime/transport",
      "/api/techtree/v1/tree/nodes/{id}",
    ],
  }),
  defineTechtreeGroup({
    commands: [
      "techtree main fetch",
      "techtree main verify",
      "techtree bbh draft pull",
      "techtree review pull",
    ],
    owner: "techtree",
    status: "current-local-and-api",
    note: "Local workspace workflow plus still-live backend endpoints.",
    pathTemplates: [
      "/api/techtree/v1/runtime/nodes/{id}",
      "/api/techtree/v1/runtime/artifacts/{id}",
      "/api/techtree/v1/runtime/artifacts/{id}/parents",
      "/api/techtree/v1/runtime/artifacts/{id}/children",
      "/api/techtree/v1/runtime/artifacts/{id}/runs",
      "/api/techtree/v1/runtime/runs/{id}",
      "/api/techtree/v1/runtime/reviews/{id}",
      "/api/techtree/v1/runtime/search",
      "/api/techtree/v1/agent/runtime/publish/submit",
      "/api/techtree/v1/agent/runtime/runs/{id}/validate",
      "/api/techtree/v1/agent/runtime/artifacts/{id}/challenge",
      "/api/techtree/v1/agent/runtime/runs/{id}/challenge",
      "/api/techtree/v1/agent/bbh/drafts/{id}",
      "/api/techtree/v1/agent/reviews/{request_id}/packet",
    ],
  }),
] as const;

export const autolaunchApiCommandGroups = [
  defineAutolaunchGroup({
    commands: ["autolaunch agents list", "autolaunch agent <id>", "autolaunch agent readiness <id>"],
    owner: "autolaunch",
    status: "current",
    pathTemplates: [
      "/api/autolaunch/v1/agent/agents",
      "/api/autolaunch/v1/agent/agents/{id}",
      "/api/autolaunch/v1/agent/agents/{id}/readiness",
    ],
  }),
  defineAutolaunchGroup({
    commands: ["autolaunch pair", "autolaunch connect start"],
    owner: "autolaunch",
    status: "current",
    pathTemplates: [
      "/api/autolaunch/v1/agent/agent-connections",
      "/api/autolaunch/v1/agent/agent-connections/{id}",
      "/api/autolaunch/v1/app/agent-connections/{code}",
      "/api/autolaunch/v1/app/agent-connections/{code}/confirm",
    ],
  }),
  defineAutolaunchGroup({
    commands: [
      "autolaunch prelaunch wizard",
      "autolaunch prelaunch get",
      "autolaunch prelaunch validate",
      "autolaunch prelaunch publish",
    ],
    owner: "autolaunch",
    status: "current-local-and-api",
    pathTemplates: [
      "/api/autolaunch/v1/agent/prelaunch/plans",
      "/api/autolaunch/v1/agent/prelaunch/plans/{id}",
      "/api/autolaunch/v1/agent/prelaunch/plans/{id}/validate",
      "/api/autolaunch/v1/agent/prelaunch/plans/{id}/publish",
      "/api/autolaunch/v1/agent/prelaunch/plans/{id}/launch",
      "/api/autolaunch/v1/agent/prelaunch/plans/{id}/metadata",
      "/api/autolaunch/v1/agent/prelaunch/plans/{id}/metadata-preview",
      "/api/autolaunch/v1/app/prelaunch/plans",
      "/api/autolaunch/v1/app/prelaunch/plans/{id}",
      "/api/autolaunch/v1/app/prelaunch/plans/{id}/validate",
      "/api/autolaunch/v1/app/prelaunch/plans/{id}/publish",
      "/api/autolaunch/v1/app/prelaunch/plans/{id}/launch",
      "/api/autolaunch/v1/app/prelaunch/plans/{id}/metadata",
      "/api/autolaunch/v1/app/prelaunch/plans/{id}/metadata-preview",
      "/api/autolaunch/v1/app/launch/preview",
      "/api/autolaunch/v1/app/launch/jobs",
    ],
  }),
  defineAutolaunchGroup({
    commands: [
      "autolaunch launch run",
      "autolaunch launch monitor",
      "autolaunch launch finalize",
      "autolaunch jobs watch",
      "autolaunch vesting status",
      "autolaunch vesting release",
      "autolaunch vesting propose-beneficiary-rotation",
      "autolaunch vesting cancel-beneficiary-rotation",
      "autolaunch vesting execute-beneficiary-rotation",
    ],
    owner: "autolaunch",
    status: "current-local-and-api",
    pathTemplates: [
      "/api/autolaunch/v1/agent/prelaunch/plans/{id}/launch",
      "/api/autolaunch/v1/agent/launch/jobs/{id}",
      "/api/autolaunch/v1/agent/lifecycle/jobs/{id}",
      "/api/autolaunch/v1/agent/lifecycle/jobs/{id}/finalize/prepare",
      "/api/autolaunch/v1/agent/lifecycle/jobs/{id}/finalize/register",
      "/api/autolaunch/v1/app/lifecycle/jobs/{id}/vesting",
      "/api/autolaunch/v1/agent/contracts/jobs/{id}/{resource}/{action}/prepare",
    ],
  }),
  defineAutolaunchGroup({
    commands: [
      "autolaunch auctions list",
      "autolaunch auction-returns list",
      "autolaunch auction <id>",
      "autolaunch bids quote",
    ],
    owner: "autolaunch",
    status: "current",
    pathTemplates: [
      "/api/autolaunch/v1/agent/auctions",
      "/api/autolaunch/v1/agent/auction-returns",
      "/api/autolaunch/v1/agent/auctions/{id}",
      "/api/autolaunch/v1/agent/auctions/{id}/bid_quote",
    ],
  }),
  defineAutolaunchGroup({
    commands: [
      "autolaunch subjects by-token",
      "autolaunch subjects get",
      "autolaunch subjects ingress",
      "autolaunch subjects staking",
      "autolaunch subjects sweep-ingress",
      "autolaunch subjects buybacks",
      "autolaunch subjects payment-links",
      "autolaunch subjects verify",
      "autolaunch payment-links create",
      "autolaunch payment-links set-canonical",
      "autolaunch payment-links set-state",
    ],
    owner: "autolaunch",
    status: "current",
    pathTemplates: [
      "/api/autolaunch/v1/agent/subjects/{id}",
      "/api/autolaunch/v1/agent/subjects/by-token/{token}",
      "/api/autolaunch/v1/agent/subjects/{id}/ingress",
      "/api/autolaunch/v1/agent/subjects/{id}/staking",
      "/api/autolaunch/v1/agent/subjects/{id}/buybacks",
      "/api/autolaunch/v1/agent/subjects/{id}/payment-links",
      "/api/autolaunch/v1/agent/contracts/subjects/{id}/{resource}/{action}/prepare",
    ],
  }),
  defineAutolaunchGroup({
    commands: [
      "autolaunch chat list",
      "autolaunch chat read <scope>",
      "autolaunch chat send <scope>",
      "autolaunch chat unread [scope...]",
      "autolaunch chat subscribe add <scope>",
      "autolaunch chat subscribe remove <scope>",
      "autolaunch chat subscribe list",
      "autolaunch dm <subject-id|address>",
      "autolaunch dm list",
    ],
    owner: "autolaunch",
    status: "current-local-and-api",
    note: "Autolaunch chat HTTP routes; DMs are server-stored dm scopes on the agent chat routes.",
    pathTemplates: [
      "/api/autolaunch/v1/chat/channels",
      "/api/autolaunch/v1/chat/messages",
      "/api/autolaunch/v1/agent/chat/messages",
      "/api/autolaunch/v1/agent/chat/dms",
      "/api/autolaunch/v1/app/subjects/{id}",
    ],
  }),
  defineAutolaunchGroup({
    commands: ["autolaunch ens plan", "autolaunch ens prepare-ensip25", "autolaunch ens prepare-erc8004", "autolaunch ens prepare-bidirectional"],
    owner: "autolaunch",
    status: "current",
    pathTemplates: [
      "/api/autolaunch/v1/agent/ens/link/plan",
      "/api/autolaunch/v1/agent/ens/link/prepare-ensip25",
      "/api/autolaunch/v1/agent/ens/link/prepare-erc8004",
      "/api/autolaunch/v1/agent/ens/link/prepare-bidirectional",
    ],
  }),
  defineAutolaunchGroup({
    commands: [
      "autolaunch contracts admin",
      "autolaunch contracts job",
      "autolaunch contracts subject",
      "autolaunch contracts verify",
      "autolaunch strategy migrate",
      "autolaunch auction claim-unused-tokens",
      "autolaunch strategy sweep-token",
      "autolaunch strategy sweep-quote-token",
      "autolaunch fee-registry get",
      "autolaunch fee-vault get",
      "autolaunch fee-vault withdraw-regent",
      "autolaunch splitter get",
      "autolaunch splitter accept-ownership",
      "autolaunch splitter set-paused",
      "autolaunch splitter set-label",
      "autolaunch splitter propose-eligible-revenue-share",
      "autolaunch splitter cancel-eligible-revenue-share",
      "autolaunch splitter activate-eligible-revenue-share",
      "autolaunch splitter propose-treasury-recipient-rotation",
      "autolaunch splitter cancel-treasury-recipient-rotation",
      "autolaunch splitter execute-treasury-recipient-rotation",
      "autolaunch splitter sweep-treasury-residual",
      "autolaunch splitter sweep-treasury-reserved",
      "autolaunch splitter reassign-dust",
      "autolaunch ingress create",
      "autolaunch ingress set-default",
      "autolaunch ingress set-label",
      "autolaunch ingress rescue",
      "autolaunch registry get",
      "autolaunch registry set-subject-manager",
      "autolaunch registry link-identity",
      "autolaunch registry rotate-safe",
      "autolaunch factory revenue-share set-authorized-creator",
      "autolaunch factory revenue-ingress set-authorized-creator",
    ],
    owner: "autolaunch",
    status: "current",
    pathTemplates: [
      "/api/autolaunch/v1/app/contracts/admin",
      "/api/autolaunch/v1/agent/contracts/jobs/{id}",
      "/api/autolaunch/v1/app/contracts/subjects/{id}",
      "/api/autolaunch/v1/agent/contracts/jobs/{id}/{resource}/{action}/prepare",
      "/api/autolaunch/v1/agent/contracts/subjects/{id}/{resource}/{action}/prepare",
      "/api/autolaunch/v1/app/contracts/admin/{resource}/{action}/prepare",
    ],
  }),
] as const;

export const platformApiCommandGroups = [
  definePlatformGroup({
    commands: ["agentbook register", "agentbook sessions watch", "agentbook lookup"],
    owner: "platform",
    status: "current",
    pathTemplates: [
      "/api/platform/agentbook/sessions",
      "/api/platform/agentbook/sessions/{id}",
      "/api/platform/agentbook/lookup",
    ],
  }),
  definePlatformGroup({
    commands: [
      "platform auth login",
      "platform auth status",
      "platform auth logout",
      "platform formation doctor",
      "platform formation status",
      "platform projection",
      "platform billing account",
      "platform billing usage",
      "platform billing spend-controls set",
      "platform billing topup",
      "platform company runtime",
      "platform company pause",
      "platform company resume",
      "agent chat",
    ],
    owner: "platform",
    status: "current",
    pathTemplates: [
      "/api/platform/auth/privy/csrf",
      "/api/platform/auth/privy/session",
      "/api/platform/auth/privy/profile",
      "/api/platform/formation",
      "/api/platform/formation/doctor",
      "/api/platform/projection",
      "/api/platform/billing/account",
      "/api/platform/billing/usage",
      "/api/platform/billing/spend-controls",
      "/api/platform/billing/topups/checkout",
      "/api/platform/agents/{slug}/runtime",
      "/api/platform/sprites/{slug}/pause",
      "/api/platform/sprites/{slug}/resume",
      "/api/platform/sprites/{slug}/message",
    ],
  }),
  definePlatformGroup({
    commands: [
      "service init",
      "service test",
      "service price set",
      "service publish",
      "service pause",
      "service resume",
      "service runs",
      "service logs",
      "service catalog check",
    ],
    owner: "platform",
    status: "current",
    pathTemplates: [
      "/api/platform/agents/{slug}/service-definitions",
      "/api/platform/agents/{slug}/service-definitions/{service_slug}",
      "/api/platform/agents/{slug}/service-definitions/{service_slug}/sandbox-test",
      "/api/platform/agents/{slug}/service-definitions/{service_slug}/pricing",
      "/api/platform/agents/{slug}/service-definitions/{service_slug}/publish",
      "/api/platform/agents/{slug}/service-definitions/{service_slug}/pause",
      "/api/platform/agents/{slug}/service-definitions/{service_slug}/resume",
      "/api/platform/agents/{slug}/service-definitions/{service_slug}/invocations",
      "/api/platform/agents/{slug}/service-definitions/{service_slug}/catalog-readiness",
    ],
  }),
  definePlatformGroup({
    commands: [
      "work create",
      "work list",
      "work get",
      "work run",
      "work cancel",
      "work retry",
      "work watch",
      "work local-loop",
      "runtime create",
      "runtime get",
      "runtime checkpoint",
      "runtime restore",
      "runtime pause",
      "runtime resume",
      "runtime services",
      "runtime health",
      "agent connect hosted-hermes",
      "agent connect hermes",
      "agent connect openclaw",
      "agent link",
      "agent execution-pool",
    ],
    owner: "platform",
    status: "current",
    pathTemplates: [
      "/api/platform/companies/{company_id}/rwr/work-items",
      "/api/platform/companies/{company_id}/rwr/work-items/{work_item_id}",
      "/api/platform/companies/{company_id}/rwr/work-items/{work_item_id}/runs",
      "/api/platform/companies/{company_id}/rwr/runs/{run_id}/cancel",
      "/api/platform/companies/{company_id}/rwr/runs/{run_id}/retry",
      "/api/platform/companies/{company_id}/rwr/runs/{run_id}/events",
      "/api/platform/companies/{company_id}/rwr/runs/{run_id}/artifacts",
      "/api/platform/companies/{company_id}/rwr/runs/{run_id}/delegations",
      "/api/platform/companies/{company_id}/rwr/runtimes",
      "/api/platform/companies/{company_id}/rwr/runtimes/{runtime_id}",
      "/api/platform/companies/{company_id}/rwr/runtimes/{runtime_id}/checkpoint",
      "/api/platform/companies/{company_id}/rwr/runtimes/{runtime_id}/restore",
      "/api/platform/companies/{company_id}/rwr/runtimes/{runtime_id}/pause",
      "/api/platform/companies/{company_id}/rwr/runtimes/{runtime_id}/resume",
      "/api/platform/companies/{company_id}/rwr/runtimes/{runtime_id}/services",
      "/api/platform/companies/{company_id}/rwr/runtimes/{runtime_id}/health",
      "/api/platform/companies/{company_id}/rwr/workers",
      "/api/platform/companies/{company_id}/rwr/workers/{worker_id}/heartbeat",
      "/api/platform/companies/{company_id}/rwr/workers/{worker_id}/assignments",
      "/api/platform/companies/{company_id}/rwr/assignments/{assignment_id}/claim",
      "/api/platform/companies/{company_id}/rwr/assignments/{assignment_id}/release",
      "/api/platform/companies/{company_id}/rwr/assignments/{assignment_id}/complete",
      "/api/platform/companies/{company_id}/rwr/agents/{source_id}/relationships",
      "/api/platform/companies/{company_id}/rwr/agents/{manager_id}/execution-pool",
    ],
  }),
  definePlatformGroup({
    commands: [
      "regent-staking get",
      "regent-staking account",
      "regent-staking verify",
      "regent-staking stake",
      "regent-staking unstake",
      "regent-staking claim-usdc",
      "regent-staking claim-regent",
      "regent-staking claim-and-restake-regent",
    ],
    owner: "platform",
    status: "current",
    pathTemplates: [
      "/api/shared/regent/staking",
      "/api/shared/regent/staking/account/{address}",
      "/api/shared/regent/staking/stake",
      "/api/shared/regent/staking/unstake",
      "/api/shared/regent/staking/claim-usdc",
      "/api/shared/regent/staking/claim-regent",
      "/api/shared/regent/staking/claim-and-restake-regent",
    ],
  }),
  definePlatformGroup({
    commands: ["bug", "security-report"],
    owner: "platform",
    status: "current",
    pathTemplates: ["/api/platform/v1/agent/bug-report", "/api/platform/v1/agent/security-report"],
  }),
] as const;

export const sharedServicesApiCommandGroups = [
  defineSharedServicesGroup({
    commands: ["identity status"],
    owner: "shared-services",
    status: "current-local-and-api",
    note: "Reads local identity state and shared Regent identity receipt metadata.",
    pathTemplates: ["/api/shared/identity/status"],
  }),
  defineSharedServicesGroup({
    commands: ["identity ensure"],
    owner: "shared-services",
    status: "current-local-and-api",
    note: "Uses local wallet state plus shared Regent SIWA identity issuance.",
    pathTemplates: [
      "/api/shared/identity/status",
      "/api/shared/identity/registration-intents",
      "/api/shared/identity/registration-completions",
      "/api/shared/identity/siwa/nonce",
      "/api/shared/identity/siwa/verify",
    ],
  }),
  defineSharedServicesGroup({
    commands: ["ens set-primary"],
    owner: "shared-services",
    status: "current",
    pathTemplates: ["/api/platform/ens/prepare-primary"],
  }),
] as const;

export const apiCommandOwnership = [
  ...techtreeApiCommandGroups,
  ...autolaunchApiCommandGroups,
  ...platformApiCommandGroups,
  ...sharedServicesApiCommandGroups,
] as const;
