import type { paths as AutolaunchPaths } from "../generated/autolaunch-openapi.js";
import type { paths as PlatformPaths } from "../generated/platform-openapi.js";
import type { paths as RegentServicePaths } from "../generated/regent-services-openapi.js";
import type { paths as TechtreePaths } from "../generated/techtree-openapi.js";

export type ApiContractOwner = "techtree" | "autolaunch" | "platform" | "shared-services";
export type ApiCommandStatus = "current" | "current-hybrid" | "stale" | "remove-before-freeze";

export interface ApiCommandGroup {
  readonly commands: readonly string[];
  readonly owner: ApiContractOwner;
  readonly status: ApiCommandStatus;
  readonly note?: string;
  readonly pathTemplates: readonly string[];
}

const defineTechtreeGroup = <
  const TPaths extends readonly (keyof TechtreePaths)[],
>(
  group: Omit<ApiCommandGroup, "pathTemplates"> & {
    readonly pathTemplates: TPaths;
  },
) => group;

const defineAutolaunchGroup = <
  const TPaths extends readonly (keyof AutolaunchPaths)[],
>(
  group: Omit<ApiCommandGroup, "pathTemplates"> & {
    readonly pathTemplates: TPaths;
  },
) => group;

const definePlatformGroup = <
  const TPaths extends readonly (keyof PlatformPaths)[],
>(
  group: Omit<ApiCommandGroup, "pathTemplates"> & {
    readonly pathTemplates: TPaths;
  },
) => group;

const defineSharedServicesGroup = <
  const TPaths extends readonly ((keyof RegentServicePaths) | (keyof PlatformPaths))[],
>(
  group: Omit<ApiCommandGroup, "pathTemplates"> & {
    readonly pathTemplates: TPaths;
  },
) => group;

export const techtreeApiCommandGroups = [
  defineTechtreeGroup({
    commands: [
      "techtree status",
      "techtree start",
      "techtree activity",
      "techtree search",
      "techtree nodes list",
    ],
    owner: "techtree",
    status: "current",
    pathTemplates: ["/v1/tree/activity", "/v1/tree/search", "/v1/tree/nodes"],
  }),
  defineTechtreeGroup({
    commands: [
      "techtree node get <id>",
      "techtree node children <id>",
      "techtree node comments <id>",
      "techtree node work-packet <id>",
      "techtree node lineage list",
      "techtree node lineage claim",
      "techtree node lineage withdraw",
      "techtree node cross-chain-links list",
      "techtree node cross-chain-links create",
      "techtree node cross-chain-links clear",
      "techtree node create",
      "techtree comment add",
    ],
    owner: "techtree",
    status: "current",
    pathTemplates: [
      "/v1/tree/nodes/{id}",
      "/v1/tree/nodes/{id}/children",
      "/v1/tree/nodes/{id}/comments",
      "/v1/tree/nodes/{id}/lineage",
      "/v1/agent/tree/nodes/{id}/lineage",
      "/v1/agent/tree/nodes/{id}/lineage/claims",
      "/v1/tree/nodes/{id}/lineage/claims",
      "/v1/tree/nodes/{id}/lineage/claims/{claim_id}",
      "/v1/agent/tree/nodes/{id}/cross-chain-links",
      "/v1/tree/nodes/{id}/cross-chain-links",
      "/v1/tree/nodes/{id}/cross-chain-links/current",
      "/v1/tree/nodes",
      "/v1/tree/comments",
      "/v1/tree/nodes/{id}/work-packet",
    ],
  }),
  defineTechtreeGroup({
    commands: [
      "techtree watch <id>",
      "techtree watch list",
      "techtree unwatch <id>",
      "techtree star <id>",
      "techtree unstar <id>",
      "techtree inbox",
      "techtree opportunities",
      "techtree watch tail",
      "techtree identities list",
      "techtree identities mint",
    ],
    owner: "techtree",
    status: "current",
    pathTemplates: [
      "/v1/agent/watches",
      "/v1/tree/nodes/{id}/watch",
      "/v1/tree/nodes/{id}/star",
      "/v1/agent/inbox",
      "/v1/agent/opportunities",
    ],
  }),
  defineTechtreeGroup({
    commands: [
      "techtree autoskill init skill",
      "techtree autoskill init eval",
      "techtree autoskill notebook pair",
      "techtree autoskill publish skill",
      "techtree autoskill publish eval",
      "techtree autoskill publish result",
      "techtree autoskill review",
      "techtree autoskill listing create",
      "techtree autoskill buy",
      "techtree autoskill refund",
      "techtree autoskill pull",
    ],
    owner: "techtree",
    status: "current",
    pathTemplates: [
      "/v1/agent/autoskill/skills",
      "/v1/agent/autoskill/evals",
      "/v1/agent/autoskill/results",
      "/v1/agent/autoskill/reviews/community",
      "/v1/agent/autoskill/reviews/replicable",
      "/v1/agent/autoskill/versions/{id}/listings",
      "/v1/agent/autoskill/versions/{id}/bundle",
      "/v1/agent/tree/nodes/{id}/payload",
    ],
  }),
  defineTechtreeGroup({
    commands: [
      "techtree science-tasks list",
      "techtree science-tasks get",
      "techtree science-tasks init",
      "techtree science-tasks checklist",
      "techtree science-tasks evidence",
      "techtree science-tasks export",
      "techtree science-tasks submit",
      "techtree science-tasks review-update",
      "techtree science-tasks review-loop",
    ],
    owner: "techtree",
    status: "current",
    pathTemplates: [
      "/v1/science-tasks",
      "/v1/science-tasks/{id}",
      "/v1/agent/science-tasks",
      "/v1/agent/science-tasks/{id}/checklist",
      "/v1/agent/science-tasks/{id}/evidence",
      "/v1/agent/science-tasks/{id}/submit",
      "/v1/agent/science-tasks/{id}/review-update",
    ],
  }),
  defineTechtreeGroup({
    commands: [
      "techtree science set-goal",
      "techtree science agent set <agent>",
      "techtree science run",
    ],
    owner: "techtree",
    status: "current",
    note: "Terminal Science runs execute locally and publish through Techtree when requested.",
    pathTemplates: [
      "/v1/science/goals",
      "/v1/science/goals/{goal_id}",
      "/v1/science/goals/active",
      "/v1/science/runs",
      "/v1/science/runs/{run_id}",
      "/v1/science/runs/{run_id}/artifacts",
      "/v1/science/runs/{run_id}/publish",
      "/v1/science/tasks/resolve",
    ],
  }),
  defineTechtreeGroup({
    commands: [
      "techtree benchmarks list",
      "techtree benchmarks get <capsule_id>",
      "techtree benchmarks scoreboard <capsule_id>",
      "techtree benchmarks reliability <capsule_id>",
      "techtree benchmarks capsule init",
      "techtree benchmarks capsule pack",
      "techtree benchmarks capsule submit",
      "techtree benchmarks run materialize",
      "techtree benchmarks run submit",
      "techtree benchmarks run repeat",
      "techtree benchmarks validate",
    ],
    owner: "techtree",
    status: "current-hybrid",
    note: "Local capsule packaging plus Techtree benchmark HTTP endpoints.",
    pathTemplates: [
      "/v1/benchmarks/capsules",
      "/v1/benchmarks/capsules/{id}",
      "/v1/benchmarks/capsules/{id}/versions",
      "/v1/benchmarks/capsules/{id}/scoreboard",
      "/v1/benchmarks/capsules/{id}/reliability",
      "/v1/benchmarks/attempts/{id}",
      "/v1/benchmarks/attempts/{id}/validations",
      "/v1/benchmarks/harnesses/{id}",
      "/v1/agent/benchmarks/capsules",
      "/v1/agent/benchmarks/capsules/{id}/versions",
      "/v1/agent/benchmarks/capsules/{id}/review-ready",
      "/v1/agent/benchmarks/capsules/{id}/publish",
      "/v1/agent/benchmarks/harnesses",
      "/v1/agent/benchmarks/attempts",
      "/v1/agent/benchmarks/attempts/repeat-group",
      "/v1/agent/benchmarks/validations",
      "/v1/agent/benchmarks/imports",
      "/v1/agent/benchmarks/capsules/{id}/reliability/recompute",
    ],
  }),
  defineTechtreeGroup({
    commands: [
      "techtree fold policy init",
      "techtree fold status",
      "techtree fold proof",
      "techtree fold report",
    ],
    owner: "techtree",
    status: "current-hybrid",
    note: "Techtree Fold policy, proof reads, and evidence reporting.",
    pathTemplates: [
      "/v1/benchmarks/attempts/{id}/proof",
      "/v1/agent/benchmarks/verifier-receipts",
      "/v1/agent/fold/status",
      "/v1/agent/fold/policy",
      "/v1/agent/fold/evidence-packet",
    ],
  }),
  defineTechtreeGroup({
    commands: [
      "techtree work",
      "techtree work list",
      "techtree work next",
      "techtree work accept",
      "techtree work publish",
    ],
    owner: "techtree",
    status: "current-hybrid",
    note: "Agent-ready Techtree work discovery, acceptance, and publication handoff.",
    pathTemplates: [
      "/v1/work",
      "/v1/work/next",
      "/v1/agent/work/{id}/accept",
    ],
  }),
  defineTechtreeGroup({
    commands: [
      "techtree notebooks init",
      "techtree notebooks pair",
      "techtree notebooks publish",
    ],
    owner: "techtree",
    status: "current-hybrid",
    note: "Paper and freeform marimo notebook workspace creation and Techtree publication.",
    pathTemplates: [
      "/v1/tree/nodes",
    ],
  }),
  defineTechtreeGroup({
    commands: [
      "techtree tech status",
      "techtree tech epochs current",
      "techtree tech leaderboards list",
      "techtree tech leaderboards register",
      "techtree tech leaderboards confirm",
      "techtree tech rewards list",
      "techtree tech rewards proof",
      "techtree tech rewards claim",
      "techtree tech rewards root prepare",
      "techtree tech rewards root confirm",
      "techtree tech withdraw",
    ],
    owner: "techtree",
    status: "current",
    note: "TECH reward reads and prepared wallet transactions.",
    pathTemplates: [
      "/v1/tech/status",
      "/v1/tech/epochs/current",
      "/v1/tech/leaderboards",
      "/v1/tech/rewards",
      "/v1/tech/rewards/proof",
      "/v1/agent/tech/rewards/claim/prepare",
      "/v1/agent/tech/withdraw/prepare",
      "/v1/agent/tech/leaderboards/register/prepare",
      "/v1/agent/tech/leaderboards/register/confirm",
      "/v1/agent/tech/rewards/root/prepare",
      "/v1/agent/tech/rewards/root/confirm",
    ],
  }),
  defineTechtreeGroup({
    commands: [
      "techtree runbook questions list",
      "techtree runbook questions get <id>",
      "techtree runbook question post",
      "techtree runbook answer post <question_id>",
      "techtree runbook answer attach-paid-solution <answer_id>",
      "techtree runbook answer vote <answer_id>",
      "techtree runbook mark-solved <question_id>",
      "techtree runbook unlock <answer_id>",
      "techtree runbook payment-address set",
      "techtree runbook invite-request <question_id>",
    ],
    owner: "techtree",
    status: "current-hybrid",
    note: "Agent-only Runbook posting, solver rooms, x402 unlock receipts, and post-purchase answer reputation.",
    pathTemplates: [
      "/v1/runbook/questions",
      "/v1/runbook/questions/{id}",
      "/v1/runbook/problems",
      "/v1/agent/runbook/payment-profile",
      "/v1/agent/runbook/questions",
      "/v1/agent/runbook/questions/{id}/answers",
      "/v1/agent/runbook/questions/{id}/mark-solved",
      "/v1/agent/runbook/questions/{id}/invite-requests",
      "/v1/agent/runbook/answers/{id}/paid-solution",
      "/v1/agent/runbook/answers/{id}/unlocks",
      "/v1/agent/runbook/answers/{id}/votes",
    ],
  }),
  defineTechtreeGroup({
    commands: [
      "techtree reviewer orcid link",
      "techtree reviewer apply",
      "techtree reviewer status",
      "techtree review list",
      "techtree review claim",
      "techtree review submit",
      "techtree certificate verify",
      "techtree bbh leaderboard",
      "techtree bbh capsules list",
      "techtree bbh capsules get",
      "techtree bbh run solve",
      "techtree bbh draft create",
      "techtree bbh draft list",
      "techtree bbh draft init",
      "techtree bbh draft propose",
      "techtree bbh draft proposals",
      "techtree bbh draft apply",
      "techtree bbh draft ready",
      "techtree bbh genome init",
      "techtree bbh genome score",
      "techtree bbh genome improve",
      "techtree bbh genome propose",
      "techtree bbh run exec",
      "techtree bbh submit",
      "techtree bbh validate",
      "techtree bbh sync",
      "techtree bbh notebook pair",
    ],
    owner: "techtree",
    status: "current",
    pathTemplates: [
      "/v1/bbh/leaderboard",
      "/v1/bbh/capsules",
      "/v1/bbh/capsules/{id}",
      "/v1/bbh/capsules/{id}/certificate",
      "/v1/bbh/genomes/{id}",
      "/v1/bbh/runs/{id}",
      "/v1/bbh/runs/{id}/validations",
      "/v1/agent/bbh/assignments/next",
      "/v1/agent/bbh/assignments/select",
      "/v1/agent/bbh/drafts",
      "/v1/agent/bbh/drafts/{id}",
      "/v1/agent/bbh/drafts/{id}/proposals",
      "/v1/agent/bbh/drafts/{id}/proposals/{proposal_id}/apply",
      "/v1/agent/bbh/drafts/{id}/ready",
      "/v1/agent/bbh/runs",
      "/v1/agent/bbh/validations",
      "/v1/agent/bbh/sync",
      "/v1/agent/reviewer/orcid/link/start",
      "/v1/agent/reviewer/orcid/link/status/{request_id}",
      "/v1/agent/reviewer/apply",
      "/v1/agent/reviewer/me",
      "/v1/agent/reviews/open",
      "/v1/agent/reviews/{request_id}/claim",
      "/v1/agent/reviews/{request_id}/submit",
    ],
  }),
  defineTechtreeGroup({
    commands: ["chatbox history", "chatbox tail", "chatbox post"],
    owner: "techtree",
    status: "current-hybrid",
    note: "Daemon-owned live transport plus Techtree public room HTTP endpoints.",
    pathTemplates: [
      "/v1/chatbox/messages",
      "/v1/agent/chatbox/messages",
      "/v1/runtime/transport",
      "/v1/runtime/transport/stream",
      "/v1/agent/runtime/transport/stream",
    ],
  }),
  defineTechtreeGroup({
    commands: [
      "techtree main fetch",
      "techtree main verify",
      "techtree bbh draft pull",
      "techtree review pull",
    ],
    owner: "techtree",
    status: "current-hybrid",
    note: "Local workspace workflow plus still-live backend endpoints.",
    pathTemplates: [
      "/v1/runtime/nodes/{id}",
      "/v1/runtime/artifacts/{id}",
      "/v1/runtime/artifacts/{id}/parents",
      "/v1/runtime/artifacts/{id}/children",
      "/v1/runtime/artifacts/{id}/runs",
      "/v1/runtime/runs/{id}",
      "/v1/runtime/reviews/{id}",
      "/v1/runtime/search",
      "/v1/agent/runtime/publish/submit",
      "/v1/agent/runtime/runs/{id}/validate",
      "/v1/agent/runtime/artifacts/{id}/challenge",
      "/v1/agent/runtime/runs/{id}/challenge",
      "/v1/agent/bbh/drafts/{id}",
      "/v1/agent/reviews/{request_id}/packet",
    ],
  }),
] as const;

export const autolaunchApiCommandGroups = [
  defineAutolaunchGroup({
    commands: ["autolaunch agents list", "autolaunch agent <id>", "autolaunch agent readiness <id>"],
    owner: "autolaunch",
    status: "current",
    pathTemplates: ["/v1/agent/agents", "/v1/agent/agents/{id}", "/v1/agent/agents/{id}/readiness"],
  }),
  defineAutolaunchGroup({
    commands: ["autolaunch pair", "autolaunch connect start"],
    owner: "autolaunch",
    status: "current",
    pathTemplates: [
      "/v1/app/agent-pairings/complete",
      "/v1/agent/agent-connections",
      "/v1/agent/agent-connections/{id}",
    ],
  }),
  defineAutolaunchGroup({
    commands: [
      "autolaunch prelaunch wizard",
      "autolaunch prelaunch get",
      "autolaunch prelaunch validate",
      "autolaunch prelaunch publish",
      "autolaunch launch preview",
    ],
    owner: "autolaunch",
    status: "current-hybrid",
    pathTemplates: [
      "/v1/agent/prelaunch/plans",
      "/v1/agent/prelaunch/plans/{id}",
      "/v1/agent/prelaunch/plans/{id}/validate",
      "/v1/agent/prelaunch/plans/{id}/publish",
      "/v1/agent/prelaunch/plans/{id}/launch",
      "/v1/agent/prelaunch/assets",
      "/v1/agent/prelaunch/plans/{id}/metadata",
      "/v1/agent/prelaunch/plans/{id}/metadata-preview",
      "/v1/agent/launch/preview",
      "/v1/agent/launch/jobs",
    ],
  }),
  defineAutolaunchGroup({
    commands: [
      "autolaunch launch run",
      "autolaunch launch state",
      "autolaunch launch monitor",
      "autolaunch launch finalize",
      "autolaunch jobs watch",
      "autolaunch vesting status",
      "autolaunch vesting release",
      "autolaunch vesting propose-beneficiary-rotation",
      "autolaunch vesting cancel-beneficiary-rotation",
      "autolaunch vesting execute-beneficiary-rotation",
    ],
    owner: "autolaunch",
    status: "current-hybrid",
    pathTemplates: [
      "/v1/agent/prelaunch/plans/{id}/launch",
      "/v1/agent/launch/creation-state",
      "/v1/agent/launch/jobs/{id}",
      "/v1/agent/lifecycle/jobs/{id}",
      "/v1/agent/lifecycle/jobs/{id}/finalize/prepare",
      "/v1/agent/lifecycle/jobs/{id}/finalize/register",
      "/v1/agent/lifecycle/jobs/{id}/vesting",
      "/v1/agent/contracts/jobs/{id}/{resource}/{action}/prepare",
    ],
  }),
  defineAutolaunchGroup({
    commands: [
      "autolaunch auctions list",
      "autolaunch auction-returns list",
      "autolaunch auction <id>",
      "autolaunch auction state <id>",
      "autolaunch bids quote",
      "autolaunch bids place",
      "autolaunch bids exit",
      "autolaunch bids claim",
    ],
    owner: "autolaunch",
    status: "current",
    pathTemplates: [
      "/v1/agent/auctions",
      "/v1/agent/auction-returns",
      "/v1/agent/auctions/{id}",
      "/v1/agent/launch/creation-state",
      "/v1/agent/auctions/{id}/bid_quote",
      "/v1/agent/auctions/{id}/bids",
      "/v1/agent/bids/{id}/return-quote-token" as keyof AutolaunchPaths,
      "/v1/agent/bids/{id}/exit",
      "/v1/agent/bids/{id}/claim",
    ],
  }),
  defineAutolaunchGroup({
    commands: [
      "autolaunch subjects create-existing-token",
      "autolaunch subjects create-deferred-autolaunch",
      "autolaunch subjects by-token",
      "autolaunch subjects get",
      "autolaunch subjects ingress",
      "autolaunch subjects staking",
      "autolaunch subjects stake",
      "autolaunch subjects unstake",
      "autolaunch subjects claim-usdc",
      "autolaunch subjects sweep-ingress",
      "autolaunch subjects buybacks",
      "autolaunch subjects settle-buyback",
      "autolaunch subjects payment-links",
      "autolaunch payment-links create",
      "autolaunch payment-links set-canonical",
      "autolaunch payment-links set-state",
      "autolaunch subjects regent-emissions",
    ],
    owner: "autolaunch",
    status: "current",
    pathTemplates: [
      "/v1/agent/subjects/existing-token/prepare",
      "/v1/agent/subjects/existing-token/confirm",
      "/v1/agent/subjects/deferred-autolaunch/prepare",
      "/v1/agent/subjects/deferred-autolaunch/confirm",
      "/v1/agent/subjects/by-token/{token}",
      "/v1/agent/subjects/{id}",
      "/v1/agent/subjects/{id}/ingress",
      "/v1/agent/subjects/{id}/staking",
      "/v1/agent/subjects/{id}/stake",
      "/v1/agent/subjects/{id}/unstake",
      "/v1/agent/subjects/{id}/claim-usdc",
      "/v1/agent/subjects/{id}/ingress/{address}/sweep",
      "/v1/agent/subjects/{id}/buybacks",
      "/v1/agent/subjects/{id}/buybacks/settle",
      "/v1/agent/subjects/{id}/payment-links",
      "/v1/agent/subjects/{id}/payment-links/{address}/canonical",
      "/v1/agent/subjects/{id}/payment-links/{address}/state",
      "/v1/agent/subjects/{id}/regent-emissions",
    ],
  }),
  defineAutolaunchGroup({
    commands: ["autolaunch ens plan", "autolaunch ens prepare-ensip25", "autolaunch ens prepare-erc8004", "autolaunch ens prepare-bidirectional"],
    owner: "autolaunch",
    status: "current",
    pathTemplates: ["/v1/agent/ens/link/plan", "/v1/agent/ens/link/prepare-ensip25", "/v1/agent/ens/link/prepare-erc8004", "/v1/agent/ens/link/prepare-bidirectional"],
  }),
  defineAutolaunchGroup({
    commands: [
      "autolaunch contracts admin",
      "autolaunch contracts job",
      "autolaunch contracts subject",
      "autolaunch strategy migrate",
      "autolaunch strategy sweep-token",
      "autolaunch strategy sweep-quote-token",
      "autolaunch fee-registry get",
      "autolaunch fee-vault get",
      "autolaunch fee-vault withdraw-regent",
      "autolaunch splitter get",
      "autolaunch splitter accept-ownership",
      "autolaunch splitter set-paused",
      "autolaunch splitter set-label",
      "autolaunch splitter propose-eligible-revenue-share",
      "autolaunch splitter cancel-eligible-revenue-share",
      "autolaunch splitter activate-eligible-revenue-share",
      "autolaunch splitter propose-treasury-recipient-rotation",
      "autolaunch splitter cancel-treasury-recipient-rotation",
      "autolaunch splitter execute-treasury-recipient-rotation",
      "autolaunch splitter sweep-treasury-residual",
      "autolaunch splitter sweep-treasury-reserved",
      "autolaunch splitter reassign-dust",
      "autolaunch ingress create",
      "autolaunch ingress set-default",
      "autolaunch ingress set-label",
      "autolaunch ingress rescue",
      "autolaunch registry get",
      "autolaunch registry set-subject-manager",
      "autolaunch registry link-identity",
      "autolaunch registry rotate-safe",
      "autolaunch factory revenue-share set-authorized-creator",
      "autolaunch factory revenue-ingress set-authorized-creator",
    ],
    owner: "autolaunch",
    status: "current",
    pathTemplates: [
      "/v1/agent/contracts/admin",
      "/v1/agent/contracts/jobs/{id}",
      "/v1/agent/contracts/subjects/{id}",
      "/v1/agent/contracts/jobs/{id}/{resource}/{action}/prepare",
      "/v1/agent/contracts/subjects/{id}/{resource}/{action}/prepare",
      "/v1/agent/contracts/admin/{resource}/{action}/prepare",
    ],
  }),
] as const;

export const platformApiCommandGroups = [
  definePlatformGroup({
    commands: ["agentbook register", "agentbook sessions watch", "agentbook lookup"],
    owner: "platform",
    status: "current",
    pathTemplates: [
      "/api/agentbook/sessions",
      "/api/agentbook/sessions/{id}",
      "/api/agentbook/lookup",
    ],
  }),
  definePlatformGroup({
    commands: [
      "platform auth login",
      "platform auth status",
      "platform auth logout",
      "platform formation doctor",
      "platform formation status",
      "platform projection",
      "platform billing account",
      "platform billing usage",
      "platform billing spend-controls set",
      "platform company runtime",
    ],
    owner: "platform",
    status: "current",
    pathTemplates: [
      "/api/auth/privy/csrf",
      "/api/auth/privy/session",
      "/api/auth/privy/profile",
      "/api/agent-platform/formation",
      "/api/agent-platform/formation/doctor",
      "/api/agent-platform/projection",
      "/api/agent-platform/billing/account",
      "/api/agent-platform/billing/usage",
      "/api/agent-platform/billing/spend-controls",
      "/api/agent-platform/agents/{slug}/runtime",
    ],
  }),
  definePlatformGroup({
    commands: [
      "work create",
      "work list",
      "work get",
      "work run",
      "work watch",
      "work local-loop",
      "runtime create",
      "runtime get",
      "runtime checkpoint",
      "runtime restore",
      "runtime pause",
      "runtime resume",
      "runtime services",
      "runtime health",
      "agent connect hermes",
      "agent connect openclaw",
      "agent link",
      "agent execution-pool",
    ],
    owner: "platform",
    status: "current",
    pathTemplates: [
      "/api/agent-platform/companies/{company_id}/rwr/work-items",
      "/api/agent-platform/companies/{company_id}/rwr/work-items/{work_item_id}",
      "/api/agent-platform/companies/{company_id}/rwr/work-items/{work_item_id}/runs",
      "/api/agent-platform/companies/{company_id}/rwr/runs/{run_id}/events",
      "/api/agent-platform/companies/{company_id}/rwr/runs/{run_id}/artifacts",
      "/api/agent-platform/companies/{company_id}/rwr/runs/{run_id}/delegations",
      "/api/agent-platform/companies/{company_id}/rwr/runtimes",
      "/api/agent-platform/companies/{company_id}/rwr/runtimes/{runtime_id}",
      "/api/agent-platform/companies/{company_id}/rwr/runtimes/{runtime_id}/checkpoint",
      "/api/agent-platform/companies/{company_id}/rwr/runtimes/{runtime_id}/restore",
      "/api/agent-platform/companies/{company_id}/rwr/runtimes/{runtime_id}/pause",
      "/api/agent-platform/companies/{company_id}/rwr/runtimes/{runtime_id}/resume",
      "/api/agent-platform/companies/{company_id}/rwr/runtimes/{runtime_id}/services",
      "/api/agent-platform/companies/{company_id}/rwr/runtimes/{runtime_id}/health",
      "/api/agent-platform/companies/{company_id}/rwr/workers",
      "/api/agent-platform/companies/{company_id}/rwr/workers/{worker_id}/heartbeat",
      "/api/agent-platform/companies/{company_id}/rwr/workers/{worker_id}/assignments",
      "/api/agent-platform/companies/{company_id}/rwr/assignments/{assignment_id}/claim",
      "/api/agent-platform/companies/{company_id}/rwr/assignments/{assignment_id}/release",
      "/api/agent-platform/companies/{company_id}/rwr/assignments/{assignment_id}/complete",
      "/api/agent-platform/companies/{company_id}/rwr/agents/{source_id}/relationships",
      "/api/agent-platform/companies/{company_id}/rwr/agents/{manager_id}/execution-pool",
    ],
  }),
  definePlatformGroup({
    commands: [
      "regent-staking get",
      "regent-staking account",
      "regent-staking stake",
      "regent-staking unstake",
      "regent-staking claim-usdc",
      "regent-staking claim-regent",
      "regent-staking claim-and-restake-regent",
    ],
    owner: "platform",
    status: "current",
    pathTemplates: [
      "/v1/agent/regent/staking",
      "/v1/agent/regent/staking/account/{address}",
      "/v1/agent/regent/staking/stake",
      "/v1/agent/regent/staking/unstake",
      "/v1/agent/regent/staking/claim-usdc",
      "/v1/agent/regent/staking/claim-regent",
      "/v1/agent/regent/staking/claim-and-restake-regent",
    ],
  }),
  definePlatformGroup({
    commands: ["bug", "security-report"],
    owner: "platform",
    status: "current",
    pathTemplates: ["/v1/agent/bug-report", "/v1/agent/security-report"],
  }),
] as const;

export const sharedServicesApiCommandGroups = [
  defineSharedServicesGroup({
    commands: ["identity status"],
    owner: "shared-services",
    status: "current-hybrid",
    note: "Reads local identity state and shared Regent identity receipt metadata.",
    pathTemplates: [],
  }),
  defineSharedServicesGroup({
    commands: ["identity ensure"],
    owner: "shared-services",
    status: "current-hybrid",
    note: "Uses local wallet state plus shared Regent SIWA identity issuance.",
    pathTemplates: [],
  }),
  defineSharedServicesGroup({
    commands: ["ens set-primary"],
    owner: "shared-services",
    status: "current",
    pathTemplates: ["/api/agent-platform/ens/prepare-primary"],
  }),
] as const;

export const apiCommandOwnership = [
  ...techtreeApiCommandGroups,
  ...autolaunchApiCommandGroups,
  ...platformApiCommandGroups,
  ...sharedServicesApiCommandGroups,
] as const;
