#!/usr/bin/env bash

set -euo pipefail

usage() {
  cat <<'EOF'
Usage: bash scripts/release-cli.sh [--dry-run] [--no-push]

Runs the Regents CLI release gate from a clean worktree, bumps the @regentslabs/cli minor
version if the checks pass, stages only the package release files it owns, creates a
Codex-style commit message, commits, and pushes.

Options:
  --dry-run  Run the release gate, simulate the version bump, and print the generated commit message without changing git state.
  --no-push  Commit locally but skip git push.
EOF
}

DRY_RUN=0
NO_PUSH=0

while (($# > 0)); do
  case "$1" in
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    --no-push)
      NO_PUSH=1
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd -- "${SCRIPT_DIR}/.." && pwd)
WORKSPACE_DIR="${REPO_ROOT}"
PACKAGE_JSON="${WORKSPACE_DIR}/packages/regents-cli/package.json"
RELEASE_STAGE_PATHS=(
  "packages/regents-cli/package.json"
  "pnpm-lock.yaml"
)

if [[ ! -f "${PACKAGE_JSON}" ]]; then
  echo "Could not find package manifest at ${PACKAGE_JSON}" >&2
  exit 1
fi

if [[ -n "$(cd "${REPO_ROOT}" && git status --porcelain)" ]]; then
  echo "Release helper requires a clean git worktree before it will bump the package version." >&2
  exit 1
fi

echo "Running Regents CLI release gate..."
(
  cd "${WORKSPACE_DIR}"
  pnpm check:openapi
  pnpm check:cli-contract
  pnpm build
  pnpm typecheck
  pnpm test
  pnpm check:pack-cli-contents
  pnpm test:pack-smoke
)

VERSION_MODE="write"
if ((DRY_RUN)); then
  VERSION_MODE="simulate"
fi

VERSION_JSON=$(node - "${PACKAGE_JSON}" "${VERSION_MODE}" <<'NODE'
const fs = require("fs");

const packagePath = process.argv[2];
const mode = process.argv[3];
const pkg = JSON.parse(fs.readFileSync(packagePath, "utf8"));
const [major, minor] = String(pkg.version).split(".").map((value) => Number.parseInt(value, 10));

if (!Number.isInteger(major) || !Number.isInteger(minor)) {
  throw new Error(`Unsupported semver version: ${pkg.version}`);
}

const nextVersion = `${major}.${minor + 1}.0`;
const updateDependencyVersion = (sections, packageName, previousVersion, nextVersionValue) => {
  for (const section of sections) {
    if (!pkg[section] || typeof pkg[section][packageName] !== "string") {
      continue;
    }

    pkg[section][packageName] = pkg[section][packageName].replace(previousVersion, nextVersionValue);
  }
};

const previousVersion = pkg.version;
pkg.version = nextVersion;
updateDependencyVersion(
  ["dependencies", "devDependencies", "peerDependencies", "optionalDependencies"],
  pkg.name,
  previousVersion,
  nextVersion,
);

if (mode === "write") {
  fs.writeFileSync(packagePath, `${JSON.stringify(pkg, null, 2)}\n`);
}

process.stdout.write(
  JSON.stringify({
    name: pkg.name,
    previousVersion,
    nextVersion,
    changedPaths: ["packages/regents-cli/package.json"],
  }),
);
NODE
)

PACKAGE_NAME=$(node -e 'const payload = JSON.parse(process.argv[1]); process.stdout.write(payload.name);' "${VERSION_JSON}")
PREVIOUS_VERSION=$(node -e 'const payload = JSON.parse(process.argv[1]); process.stdout.write(payload.previousVersion);' "${VERSION_JSON}")
NEXT_VERSION=$(node -e 'const payload = JSON.parse(process.argv[1]); process.stdout.write(payload.nextVersion);' "${VERSION_JSON}")

echo "Version bumped: ${PACKAGE_NAME} ${PREVIOUS_VERSION} -> ${NEXT_VERSION}"

STAGED_FILES=()
if ((DRY_RUN)); then
  while IFS= read -r staged_file; do
    if [[ -n "${staged_file}" ]]; then
      STAGED_FILES+=("${staged_file}")
    fi
  done < <(
    node -e 'const payload = JSON.parse(process.argv[1]); for (const file of payload.changedPaths || []) console.log(file);' "${VERSION_JSON}"
  )
else
  (
    cd "${REPO_ROOT}"
    git add -- "${RELEASE_STAGE_PATHS[@]}"
  )

  while IFS= read -r staged_file; do
    STAGED_FILES+=("${staged_file}")
  done < <(
    cd "${REPO_ROOT}" &&
      git diff --cached --name-only -- "${RELEASE_STAGE_PATHS[@]}"
  )
fi

if ((${#STAGED_FILES[@]} == 0)); then
  echo "No staged files found in the release scope after git add." >&2
  exit 1
fi

BRANCH_NAME=$(cd "${REPO_ROOT}" && git rev-parse --abbrev-ref HEAD)
MESSAGE_FILE=$(mktemp)
trap 'rm -f "${MESSAGE_FILE}"' EXIT

{
  echo "codex: release ${PACKAGE_NAME} v${NEXT_VERSION}"
  echo
  echo "Generated by the Codex Regents CLI release helper after a passing release gate."
  echo
  echo "Validation:"
  echo "- pnpm check:openapi"
  echo "- pnpm check:cli-contract"
  echo "- pnpm build"
  echo "- pnpm typecheck"
  echo "- pnpm test"
  echo "- pnpm check:pack-cli-contents"
  echo "- pnpm test:pack-smoke"
  echo
  echo "Version:"
  echo "- ${PACKAGE_NAME} ${PREVIOUS_VERSION} -> ${NEXT_VERSION}"
  echo "- branch ${BRANCH_NAME}"
  echo
  echo "Staged files:"
  for index in "${!STAGED_FILES[@]}"; do
    if ((index == 12)); then
      remaining=$((${#STAGED_FILES[@]} - 12))
      echo "- ... plus ${remaining} more file(s)"
      break
    fi
    echo "- ${STAGED_FILES[$index]}"
  done
} > "${MESSAGE_FILE}"

if ((DRY_RUN)); then
  echo
  echo "Dry run complete. Generated commit message:"
  echo "----------------------------------------"
  cat "${MESSAGE_FILE}"
  echo "----------------------------------------"
  exit 0
fi

(
  cd "${REPO_ROOT}"
  git commit -F "${MESSAGE_FILE}"
)

if ((NO_PUSH)); then
  echo "Commit created locally. Skipping push because --no-push was provided."
  exit 0
fi

(
  cd "${REPO_ROOT}"
  git push
)

echo "Release commit pushed."
