export const CLI_COMMANDS = [
  "agent harness list",
  "agent init",
  "agent profile list",
  "agent profile show",
  "agent status",
  "agentbook lookup",
  "agentbook register",
  "agentbook sessions watch",
  "auth login",
  "auth logout",
  "auth status",
  "autolaunch agent <id>",
  "autolaunch agent readiness <id>",
  "autolaunch agents list",
  "autolaunch auction <id>",
  "autolaunch auction-returns list",
  "autolaunch auctions list",
  "autolaunch bids claim",
  "autolaunch bids exit",
  "autolaunch bids place",
  "autolaunch bids quote",
  "autolaunch contracts admin",
  "autolaunch contracts job",
  "autolaunch contracts subject",
  "autolaunch ens plan",
  "autolaunch ens prepare-bidirectional",
  "autolaunch ens prepare-ensip25",
  "autolaunch ens prepare-erc8004",
  "autolaunch factory revenue-ingress set-authorized-creator",
  "autolaunch factory revenue-share set-authorized-creator",
  "autolaunch fee-registry show",
  "autolaunch fee-vault show",
  "autolaunch fee-vault withdraw-regent",
  "autolaunch fee-vault withdraw-treasury",
  "autolaunch holdings claim-and-stake-emissions",
  "autolaunch holdings claim-emissions",
  "autolaunch holdings claim-usdc",
  "autolaunch holdings stake",
  "autolaunch holdings sweep-ingress",
  "autolaunch holdings unstake",
  "autolaunch identities list",
  "autolaunch identities mint",
  "autolaunch ingress create",
  "autolaunch ingress rescue",
  "autolaunch ingress set-default",
  "autolaunch ingress set-label",
  "autolaunch jobs watch",
  "autolaunch launch create",
  "autolaunch launch finalize",
  "autolaunch launch monitor",
  "autolaunch launch preview",
  "autolaunch launch run",
  "autolaunch prelaunch publish",
  "autolaunch prelaunch show",
  "autolaunch prelaunch validate",
  "autolaunch prelaunch wizard",
  "autolaunch registry link-identity",
  "autolaunch registry rotate-safe",
  "autolaunch registry set-subject-manager",
  "autolaunch registry show",
  "autolaunch safe create",
  "autolaunch safe wizard",
  "autolaunch splitter accept-ownership",
  "autolaunch splitter activate-eligible-revenue-share",
  "autolaunch splitter cancel-eligible-revenue-share",
  "autolaunch splitter cancel-treasury-recipient-rotation",
  "autolaunch splitter execute-treasury-recipient-rotation",
  "autolaunch splitter propose-eligible-revenue-share",
  "autolaunch splitter propose-treasury-recipient-rotation",
  "autolaunch splitter reassign-dust",
  "autolaunch splitter set-label",
  "autolaunch splitter set-paused",
  "autolaunch splitter set-protocol-recipient",
  "autolaunch splitter show",
  "autolaunch splitter sweep-protocol-reserve",
  "autolaunch splitter sweep-treasury-reserved",
  "autolaunch splitter sweep-treasury-residual",
  "autolaunch strategy migrate",
  "autolaunch strategy sweep-currency",
  "autolaunch strategy sweep-token",
  "autolaunch subjects claim-and-stake-emissions",
  "autolaunch subjects claim-emissions",
  "autolaunch subjects claim-usdc",
  "autolaunch subjects ingress",
  "autolaunch subjects show",
  "autolaunch subjects stake",
  "autolaunch subjects sweep-ingress",
  "autolaunch subjects unstake",
  "autolaunch vesting cancel-beneficiary-rotation",
  "autolaunch vesting execute-beneficiary-rotation",
  "autolaunch vesting propose-beneficiary-rotation",
  "autolaunch vesting release",
  "autolaunch vesting status",
  "balance",
  "bug",
  "chatbox history",
  "chatbox post",
  "chatbox tail",
  "config read",
  "config write",
  "create init",
  "create wallet",
  "doctor",
  "ens set-primary",
  "gossipsub status",
  "identity ensure",
  "identity status",
  "init",
  "mcp export hermes",
  "platform auth login",
  "platform auth logout",
  "platform auth status",
  "platform billing account",
  "platform billing setup",
  "platform billing topup",
  "platform billing usage",
  "platform company create",
  "platform company runtime",
  "platform formation status",
  "platform sprite pause",
  "platform sprite resume",
  "regent-staking account",
  "regent-staking claim-and-restake-regent",
  "regent-staking claim-regent",
  "regent-staking claim-usdc",
  "regent-staking show",
  "regent-staking stake",
  "regent-staking unstake",
  "run",
  "search",
  "security-report",
  "status",
  "techtree activity",
  "techtree autoskill buy",
  "techtree autoskill init eval",
  "techtree autoskill init skill",
  "techtree autoskill listing create",
  "techtree autoskill notebook pair",
  "techtree autoskill publish eval",
  "techtree autoskill publish result",
  "techtree autoskill publish skill",
  "techtree autoskill pull",
  "techtree autoskill review",
  "techtree bbh capsules get",
  "techtree bbh capsules list",
  "techtree bbh draft apply",
  "techtree bbh draft create",
  "techtree bbh draft init",
  "techtree bbh draft list",
  "techtree bbh draft proposals",
  "techtree bbh draft propose",
  "techtree bbh draft pull",
  "techtree bbh draft ready",
  "techtree bbh fetch",
  "techtree bbh genome improve",
  "techtree bbh genome init",
  "techtree bbh genome propose",
  "techtree bbh genome score",
  "techtree bbh leaderboard",
  "techtree bbh notebook pair",
  "techtree bbh run exec",
  "techtree bbh run solve",
  "techtree bbh submit",
  "techtree bbh sync",
  "techtree bbh validate",
  "techtree bbh verify",
  "techtree certificate verify",
  "techtree comment add",
  "techtree identities list",
  "techtree identities mint",
  "techtree inbox",
  "techtree main artifact compile",
  "techtree main artifact init",
  "techtree main artifact pin",
  "techtree main artifact publish",
  "techtree main fetch",
  "techtree main review compile",
  "techtree main review exec",
  "techtree main review init",
  "techtree main review pin",
  "techtree main review publish",
  "techtree main run compile",
  "techtree main run exec",
  "techtree main run init",
  "techtree main run pin",
  "techtree main run publish",
  "techtree main verify",
  "techtree node children",
  "techtree node comments",
  "techtree node create",
  "techtree node cross-chain-links clear",
  "techtree node cross-chain-links create",
  "techtree node cross-chain-links list",
  "techtree node get",
  "techtree node lineage claim",
  "techtree node lineage list",
  "techtree node lineage withdraw",
  "techtree node work-packet",
  "techtree nodes list",
  "techtree opportunities",
  "techtree review claim",
  "techtree review list",
  "techtree review pull",
  "techtree review submit",
  "techtree reviewer apply",
  "techtree reviewer orcid link",
  "techtree reviewer status",
  "techtree science-tasks checklist",
  "techtree science-tasks evidence",
  "techtree science-tasks export",
  "techtree science-tasks get",
  "techtree science-tasks init",
  "techtree science-tasks list",
  "techtree science-tasks review-loop",
  "techtree science-tasks review-update",
  "techtree science-tasks submit",
  "techtree search",
  "techtree star",
  "techtree start",
  "techtree status",
  "techtree unstar",
  "techtree unwatch",
  "techtree watch",
  "techtree watch list",
  "techtree watch tail",
  "wallet setup",
  "wallet status",
  "whoami",
  "xmtp doctor",
  "xmtp group add-admin",
  "xmtp group add-member",
  "xmtp group add-super-admin",
  "xmtp group admins",
  "xmtp group create",
  "xmtp group list",
  "xmtp group members",
  "xmtp group permissions",
  "xmtp group remove-admin",
  "xmtp group remove-member",
  "xmtp group remove-super-admin",
  "xmtp group super-admins",
  "xmtp group update-permission",
  "xmtp info",
  "xmtp init",
  "xmtp owner add",
  "xmtp owner list",
  "xmtp owner remove",
  "xmtp policy edit",
  "xmtp policy init",
  "xmtp policy show",
  "xmtp policy validate",
  "xmtp resolve",
  "xmtp revoke-other-installations",
  "xmtp rotate-db-key",
  "xmtp rotate-wallet",
  "xmtp status",
  "xmtp test dm",
  "xmtp trusted add",
  "xmtp trusted list",
  "xmtp trusted remove"
] as const;

export type CliCommandName = (typeof CLI_COMMANDS)[number];

export const cliCommandSet = new Set<string>(CLI_COMMANDS);

export const commandMatchesInput = (command: string, input: readonly string[]): boolean => {
  const commandParts = command.split(" ");
  if (commandParts.length !== input.length) {
    return false;
  }

  return commandParts.every((part, index) => part.startsWith("<") && part.endsWith(">") ? Boolean(input[index]) : part === input[index]);
};

export const knownCliCommand = (input: readonly string[]): boolean =>
  CLI_COMMANDS.some((command) => commandMatchesInput(command, input));
